// ===== MÀN 3 — DÒNG CHẢY NỘI DUNG (ADR-003): kanban 6 giai đoạn · thẻ mở popup Soạn / Duyệt (G3) / Sản xuất / Đăng =====
const GIAI_DOAN = [['Y_TUONG','Ý tưởng'],['SOAN','Soạn'],['CHO_DUYET','Chờ duyệt (G3)'],['SAN_XUAT','Sản xuất'],['DA_DANG','Đã đăng'],['DA_DO','Đã đo']];
const ND_TT = { NHAP:['Nháp','bg-slate-100 text-ink'], CHO_DUYET:['Chờ duyệt','bg-amber-100 text-amber-800'], DUYET:['Đã duyệt','bg-emerald-100 text-emerald-800'], TRA_LAI:['Trả lại','bg-rose-100 text-rose-700'] };
const BD_TT = { CHUAN_BI:['Chuẩn bị','bg-slate-100 text-ink'], DA_LEN_LICH:['Đã lên lịch','bg-sky-100 text-sky-800'], DANG_GUI:['Đang gửi (n8n/Trạm)','bg-amber-100 text-amber-800'], DA_DANG:['Đã đăng','bg-emerald-100 text-emerald-800'], LOI:['Lỗi','bg-rose-100 text-rose-700'] };
const CT_KEYS = { POST:[['hashtag','Hashtag']], ANH:[['chu_phu','Chữ phụ'],['caption','Caption đăng kèm'],['hashtag','Hashtag'],['brief','Brief cho designer']], CAROUSEL:[['caption','Caption đăng kèm'],['hashtag','Hashtag']], VIDEO:[] };
function banDangFE(nd){ const secs=nd.sections||[]; const ct=nd.chi_tiet||{}; const than=secs.map(x=>x.text); const dd=nd.dinh_dang||'VIDEO'; let p; if(dd==='POST') p=[nd.hook,...than,nd.cta,ct.hashtag]; else if(dd==='ANH') p=[ct.caption||[nd.hook,ct.chu_phu].filter(Boolean).join('\n'),nd.cta,ct.hashtag]; else if(dd==='CAROUSEL') p=[ct.caption||[nd.hook,...than].filter(Boolean).join('\n'),nd.cta,ct.hashtag]; else p=[nd.hook,...than,nd.cta]; return p.filter(Boolean).join('\n\n'); }
// Kho video thành phẩm (26/09, chủ: "tôi không thấy kho thành phẩm video" · "tôi thường dùng điện thoại" · "gắn các thông tin tracking theo dòng nội dung để quản lý sử dụng")
// Mỗi bản nháp máy dựng (VIDEO_XUAT) kèm: mã video · dòng · mục (tháng/tuần/giai đoạn) · kênh · kịch bản vN (ai soạn) · ai duyệt · máy dựng · bài đăng (kênh, link) · kết quả (xem, tương tác, đơn, doanh thu) · trạng thái dùng.
// Tất cả suy ra từ bảng gốc của dòng chảy (một nguồn); chỉ lưu thêm ma_video, muc.dong, su_dung.
const SU_DUNG={ dang:['đã đăng','bg-sky-100 text-sky-800'], chon:['chọn dùng','bg-emerald-100 text-emerald-800'], cho:['chờ quyết','bg-amber-100 text-amber-800'], bo:['đã loại','bg-slate-100 text-ink-muted'], cu:['bản cũ','bg-slate-100 text-ink-muted'] };
function KhoVideoThanhPham({ onMo }){
  const { db, goi, notify, me } = useApp(); const [het,setHet]=useState(false); const [loc,setLoc]=useState(''); const [locDong,setLocDong]=useState(''); const [mo,setMo]=useState(null); const [busy,setBusy]=useState(false); const sua=laStaff(me);
  const ts=db.tai_san||[]; const ndCua=id=>(db.noi_dung||[]).find(n=>n.id===id); const mucCua=id=>(db.muc_noi_dung||[]).find(m=>m.id===id); const kTen=id=>((db.kenh||[]).find(k=>k.id===id)||{}).ten; const pTen=id=>((db.pillars||[]).find(p=>p.id===id)||{}).ten;
  const GD=Object.fromEntries(GIAI_DOAN);
  const ds=ts.filter(t=>t.loai==='VIDEO_XUAT').map(t=>{ const nd=t.noi_dung_id?ndCua(t.noi_dung_id):null; const muc=mucCua(t.muc_id||(nd&&nd.muc_id));
    const goiD=ts.filter(g=>g.loai==='GOI_DUNG'&&((t.noi_dung_id&&g.noi_dung_id===t.noi_dung_id)||(!t.noi_dung_id&&g.muc_id===t.muc_id))).sort((a,b)=>Math.abs(Date.parse(a.created_at)-Date.parse(t.created_at))-Math.abs(Date.parse(b.created_at)-Date.parse(t.created_at)))[0];
    const moiNhat=nd&&((nd.chi_tiet||{}).video_url===t.media_url); const dy=nd&&(db.duyet||[]).filter(d=>d.doi_tuong_id===nd.id&&d.trang_thai==='DUYET').sort((a,b)=>String(b.quyet_at).localeCompare(String(a.quyet_at)))[0];
    const bd=(db.bai_dang||[]).filter(b=>b.media_url===t.media_url||(moiNhat&&nd&&b.noi_dung_id===nd.id)); const kq=(db.ket_qua||[]).filter(k=>bd.some(b=>b.id===k.bai_dang_id)||(k.ma_theo_doi&&k.ma_theo_doi===t.ma_video));
    const tong=kq.reduce((a,k)=>({xem:a.xem+(k.luot_xem||0), tt:a.tt+(k.tuong_tac||0), don:a.don+(k.so_don||0), dt:a.dt+(k.doanh_thu||0)}),{xem:0,tt:0,don:0,dt:0});
    const tt=bd.some(b=>b.trang_thai==='DA_DANG')?'dang':t.su_dung==='BO'?'bo':t.su_dung==='CHON'?'chon':moiNhat?'cho':'cu';
    return { t, nd, muc, goi:goiD, dy, bd, kq, tong, tt, dong:(muc&&muc.dong)||null }; }).sort((a,b)=>String(b.t.created_at).localeCompare(String(a.t.created_at)));
  if(!ds.length) return null;
  const dongs=[...new Set([...(db.dong_chuan||[]), ...ds.map(x=>x.dong).filter(Boolean)])];
  const loc2=ds.filter(x=>(!loc||x.tt===loc)&&(!locDong||(locDong==='-'?!x.dong:x.dong===locDong))); const hien=het?loc2:loc2.slice(0,8); const dem=k=>ds.filter(x=>x.tt===k).length;
  const dat=async(duong,body,tb)=>{ setBusy(true); const r=await goi(duong,{method:'POST',body}); setBusy(false); if(r.ok) notify(tb); else notify(r.msg,'err'); };
  const chep=(ma)=>{ try{ navigator.clipboard.writeText(ma).then(()=>notify('Đã chép mã '+ma),()=>notify('Mã video: '+ma)); }catch(e){ notify('Mã video: '+ma); } };
  const Dong=({k,v})=>v?<div className="flex gap-2"><span className="text-ink-muted w-[74px] shrink-0">{k}</span><span className="min-w-0 flex-1 break-words">{v}</span></div>:null;
  return <Card pad="p-3" className="space-y-2">
    <div className="flex items-center gap-2 flex-wrap"><SectionTitle className="!mb-0">🎬 Kho video thành phẩm ({ds.length})</SectionTitle><span className="text-[11px] text-ink-muted">bản nháp máy dựng, mới nhất trước · mỗi video kèm mã theo dõi và đường đi trong dòng chảy</span></div>
    <div className="flex gap-1.5 flex-wrap text-xs">{[['','Tất cả',ds.length],['cho','Chờ quyết',dem('cho')],['chon','Chọn dùng',dem('chon')],['dang','Đã đăng',dem('dang')],['bo','Đã loại',dem('bo')],['cu','Bản cũ',dem('cu')]].filter(x=>x[2]||!x[0]).map(([k,t,n])=><button key={k} onClick={()=>setLoc(k)} className={'rounded-full border px-2.5 py-1 '+(loc===k?'border-ink font-bold bg-white':'border-line bg-white')}>{t} · {n}</button>)}
      <select className="border border-line rounded-full px-2 py-1 bg-white" value={locDong} onChange={e=>setLocDong(e.target.value)}><option value="">mọi dòng</option>{dongs.map(d=><option key={d} value={d}>{d} · {ds.filter(x=>x.dong===d).length}</option>)}<option value="-">chưa có dòng · {ds.filter(x=>!x.dong).length}</option></select></div>
    <div className="flex gap-3 overflow-x-auto snap-x pb-1 sm:grid sm:grid-cols-3 lg:grid-cols-4 sm:overflow-visible">{hien.map(x=>{ const {t,nd,muc,goi:gd,dy,bd,tong,tt}=x; const moTT=mo===t.id; return <div key={t.id} className="rounded-xl border border-line overflow-hidden bg-white min-w-0 w-[64vw] max-w-[260px] shrink-0 snap-start sm:w-auto sm:max-w-none flex flex-col">
      <video src={t.media_url+"#t=0.1"} controls playsInline preload="metadata" className="w-full bg-black aspect-[9/16] object-contain"/>
      <div className="p-2.5 space-y-1.5 text-xs flex-1 flex flex-col">
        <div className="flex items-center gap-1.5 flex-wrap"><button onClick={()=>t.ma_video&&chep(t.ma_video)} title="Chép mã để dán vào caption / mã theo dõi kết quả" className="font-mono text-[11px] font-bold rounded-md bg-[#E0F2F4] text-[#0E7C8C] px-1.5 py-0.5">{t.ma_video||'—'} ⧉</button><Pill cls={SU_DUNG[tt][1]} className="!text-[11px]">{SU_DUNG[tt][0]}</Pill>{x.dong?<Pill cls="bg-[#F6EDD6] text-[#8A6410]" className="!text-[11px]">{x.dong}</Pill>:<Pill cls="bg-[#FFF9E8] text-[#8A6410]" className="!text-[11px]">chưa có dòng</Pill>}</div>
        <button onClick={()=>muc&&onMo(muc)} className="font-semibold text-[13px] text-left text-ink hover:underline leading-snug">{(nd&&(nd.tieu_de||nd.hook))||(muc&&muc.tieu_de)||t.ten}</button>
        <div className="text-ink-muted">{fmtDate(t.created_at)} · dựng bởi {t.created_by_name||'máy'}{bd.length?(' · '+bd.length+' bài đăng'):''}{tong.xem?(' · '+tong.xem.toLocaleString('vi-VN')+' xem'):''}{tong.don?(' · '+tong.don+' đơn'):''}</div>
        {nd&&(nd.chi_tiet||{}).thieu_hinh&&<div className="text-amber-700">⚠ Thiếu hình: {(nd.chi_tiet||{}).thieu_hinh}</div>}
        <button onClick={()=>setMo(moTT?null:t.id)} className="text-left text-[11px] font-semibold text-[#0E7C8C]">{moTT?'▾ Ẩn thông tin theo dõi':'▸ Thông tin theo dõi'}</button>
        {moTT&&<div className="rounded-lg bg-[#EFF4F6] p-2 space-y-1 text-[11px]">
          <Dong k="Mục" v={muc&&(muc.tieu_de+' · '+muc.thang+(muc.tuan?(' tuần '+muc.tuan):'')+(muc.ngay_dang?(' · đăng dự kiến '+muc.ngay_dang):''))}/>
          <Dong k="Giai đoạn" v={muc&&GD[muc.giai_doan]}/>
          <Dong k="Kênh" v={muc&&(kTen(muc.kenh_id)||'chưa gắn kênh')}/>
          <Dong k="Mục tiêu" v={muc&&[MUC_TIEU_LABEL[muc.muc_tieu], pTen(muc.pillar_id)].filter(Boolean).join(' · ')}/>
          <Dong k="Kịch bản" v={nd&&('v'+nd.phien_ban+' · '+(nd.tao_boi==='AGENT'?'máy soạn ('+(nd.created_by_name||'B4')+')':'người soạn ('+(nd.created_by_name||'')+')'))}/>
          <Dong k="Duyệt" v={dy&&(dy.quyet_boi+' · '+fmtDate(dy.quyet_at)+(dy.cham_may&&dy.cham_may.diem!=null?(' · máy chấm '+dy.cham_may.diem):''))}/>
          <Dong k="Dựng" v={(t.created_by_name||'máy')+' · '+fmtDate(t.created_at)+(gd?' · có gói CapCut':'')}/>
          <Dong k="Đăng" v={bd.length?bd.map(b=>(kTen(b.kenh_id)||'kênh ?')+' · '+((BD_TT[b.trang_thai]||[])[0]||b.trang_thai)+(b.posted_at?(' '+fmtDate(b.posted_at)):'')).join(' | '):'chưa đăng'}/>
          {bd.filter(b=>b.link).map(b=><a key={b.id} className="block underline text-[#0E7C8C] truncate" href={b.link} target="_blank" rel="noreferrer">{b.link}</a>)}
          <Dong k="Kết quả" v={x.kq.length?(tong.xem.toLocaleString('vi-VN')+' xem · '+tong.tt.toLocaleString('vi-VN')+' tương tác · '+tong.don+' đơn'+(tong.dt?(' · '+tong.dt.toLocaleString('vi-VN')+' đ'):'')):'chưa có số đo'}/>
          {sua&&muc&&<div className="flex gap-2 items-center pt-1"><span className="text-ink-muted w-[74px] shrink-0">Đổi dòng</span><select disabled={busy} className="border border-line rounded-lg px-1.5 py-1 bg-white min-w-0 flex-1" value={muc.dong||''} onChange={e=>dat('/muc/'+muc.id+'/dong',{dong:e.target.value||null},'Đã gán dòng cho mục — mọi video của mục đổi theo')}><option value="">chưa có dòng</option>{dongs.map(d=><option key={d} value={d}>{d}</option>)}</select></div>}
        </div>}
        <div className="flex gap-1.5 flex-wrap pt-1 mt-auto">{sua&&tt!=='dang'&&<button disabled={busy} onClick={()=>dat('/tai-san/'+t.id+'/su-dung',{su_dung:t.su_dung==='CHON'?null:'CHON'},t.su_dung==='CHON'?'Bỏ chọn':'Đã chọn dùng video '+(t.ma_video||''))} className={'rounded-lg border px-2.5 py-1.5 font-semibold '+(t.su_dung==='CHON'?'bg-emerald-600 border-emerald-600 text-white':'border-line')}>✓ Dùng</button>}
          {sua&&tt!=='dang'&&<button disabled={busy} onClick={()=>dat('/tai-san/'+t.id+'/su-dung',{su_dung:t.su_dung==='BO'?null:'BO'},t.su_dung==='BO'?'Đã bỏ đánh dấu loại':'Đã loại video '+(t.ma_video||''))} className={'rounded-lg border px-2.5 py-1.5 '+(t.su_dung==='BO'?'bg-slate-600 border-slate-600 text-white':'border-line')}>✕ Loại</button>}
          {gd&&<a className="rounded-lg border border-line px-2.5 py-1.5 font-semibold" href={gd.media_url} target="_blank" rel="noreferrer">📦 CapCut</a>}<a className="rounded-lg border border-line px-2.5 py-1.5" href={t.media_url} target="_blank" rel="noreferrer">⤓ Tải</a>{muc&&<button onClick={()=>onMo(muc)} className="rounded-lg border border-line px-2.5 py-1.5">Mở thẻ</button>}</div></div>
    </div>; })}</div>
    {loc2.length>8&&<button onClick={()=>setHet(!het)} className="w-full rounded-lg border border-line py-2 text-xs font-semibold bg-white">{het?'Thu gọn':'Xem tất cả '+loc2.length+' video'}</button>}
  </Card>; }
function DongChayNoiDung(){
  const { db, me } = useApp(); const buoc=db.buoc||[]; const chiXem=!laStaff(me);
  const [thang,setThang]=useState(db.hang_so.thang_nay); const [mo,setMo]=useState(null); const [locGd,setLocGd]=useState('');
  const muc=(db.muc_noi_dung||[]).filter(m=>m.thang===thang); const ndCua=m=>(db.noi_dung||[]).filter(n=>n.muc_id===m.id).sort((a,b)=>a.updated_at<b.updated_at?1:-1)[0];
  const pTen=id=>((db.pillars||[]).find(p=>p.id===id)||{}).ten||'—'; const kTen=id=>((db.kenh||[]).find(k=>k.id===id)||{}).ten||'—';
  const cua=ma=>buoc.find(b=>b.ma===ma)||{}; const cotBuoc={Y_TUONG:['B1','B3'],SOAN:['B4'],CHO_DUYET:['B5'],SAN_XUAT:['B6','B7','B8'],DA_DANG:['B9'],DA_DO:['B10']};
  const cho=(db.duyet||[]).filter(d=>d.trang_thai==='CHO'); const chanTuDuyet=((db.module_config||{}).duyet||{}).chan_tu_duyet!==false;
  const choToi=cho.filter(d=>laGat(me)&&!(chanTuDuyet&&d.nguoi_gui_id===me.id));
  const moNd=id=>{ const nd=(db.noi_dung||[]).find(n=>n.id===id); const m=nd&&(db.muc_noi_dung||[]).find(x=>x.id===nd.muc_id); if(m) setMo({muc:m, tab:'duyet'}); };
  useEffect(()=>{ if(mo){ const m=(db.muc_noi_dung||[]).find(x=>x.id===mo.muc.id); if(m&&m!==mo.muc) setMo(o=>({...o, muc:m})); } },[db]);
  return <div className="space-y-4">
    <PageHeader title="🔁 Dòng chảy nội dung" sub="Một thẻ đi hết 6 giai đoạn. Máy đẩy thẻ theo sự kiện; người chỉ vào ở cổng G3 và các việc được giao." right={<div className="flex items-center gap-2"><Input type="month" className="!w-40 !py-1.5" value={thang} onChange={e=>setThang(e.target.value)}/>{!chiXem&&<Btn variant="brand" onClick={()=>window.__go('chienluoc')}>＋ Mục mới ở Kế hoạch</Btn>}</div>}/>
    {cho.length>0 && <Card pad="p-3"><div className="flex items-center justify-between"><SectionTitle>🛂 Hàng đợi duyệt — cổng G3 ({cho.length}{laGat(me)?(' · '+choToi.length+' tới lượt bạn'):''})</SectionTitle><span className="text-[11px] text-ink-muted">máy chấm sẵn, xếp bài điểm cao trước — máy không bao giờ tự duyệt</span></div>
      {[...cho].sort((a,b)=>(b.cham_may.diem||0)-(a.cham_may.diem||0)).map(d=>{ const nd=(db.noi_dung||[]).find(n=>n.id===d.doi_tuong_id)||{}; const cm=d.cham_may||{}; return <div key={d.id} className="flex items-center gap-3 py-1.5 border-t border-line text-xs cursor-pointer hover:bg-slate-50" onClick={()=>moNd(d.doi_tuong_id)}>
        <span className={"font-display font-extrabold w-8 text-center "+((cm.diem||0)>=70?'text-emerald-600':(cm.diem||0)>=40?'text-amber-600':'text-rose-500')}>{cm.diem??'—'}</span>
        <div className="min-w-0 flex-1"><div className="font-semibold text-ink">{DINH_DANG_ICON[nd.dinh_dang]?DINH_DANG_ICON[nd.dinh_dang].split(' ')[0]:''} {nd.tieu_de||nd.hook}</div><div className="text-[11px] text-ink-muted">gửi bởi {d.nguoi_gui_ten} · {fmtDate(d.created_at)}{(cm.loi_cung||[]).length?(' · ⚠ '+cm.loi_cung.join('; ')):''}{(cm.ly_do||[]).length?(' · '+cm.ly_do.join('; ')):''}</div></div>
        {d.nguoi_gui_id===me.id&&chanTuDuyet&&<Pill>bài của bạn</Pill>}</div>; })}</Card>}
    <KhoVideoThanhPham onMo={(m)=>setMo({muc:m, tab:'sanxuat'})}/>
    <div className="flex gap-2 overflow-x-auto pb-2 snap-x">{GIAI_DOAN.map(([gd,ten])=>{ const ds=muc.filter(m=>m.giai_doan===gd); return <div key={gd} className="bg-slate-50 rounded-xl p-2 w-[72vw] max-w-[236px] sm:w-auto sm:flex-1 sm:min-w-[150px] shrink-0 snap-start">
      <div className="text-[11px] font-bold text-ink-muted mb-1 flex justify-between"><span>{ten}</span><span>{ds.length}</span></div>
      <div className="flex flex-wrap gap-1 mb-2">{cotBuoc[gd].map(ma=>{ const x=cua(ma); return <Pill key={ma} cls={MUC_CLS[x.nguoi_thuc_hien]||''} className="!text-[10.5px]" >{ma} {MUC_LABEL[x.nguoi_thuc_hien]||''}</Pill>; })}</div>
      <div className="space-y-1.5">{ds.map(m=>{ const nd=ndCua(m); return <div key={m.id} onClick={()=>setMo({muc:m, tab:gd==='CHO_DUYET'?'duyet':gd==='SAN_XUAT'?'sanxuat':gd==='DA_DANG'?'dang':'noidung'})} className="bg-white rounded-lg border border-line p-2 cursor-pointer hover:border-brand">
        <div className="text-[11px] font-semibold text-ink">{(DINH_DANG_ICON[m.dinh_dang]||'📄').split(' ')[0]} {m.tieu_de}</div>
        <div className="text-[11px] text-ink-muted mt-0.5">{pTen(m.pillar_id)} · {kTen(m.kenh_id)} · <Pill cls={MUC_TIEU_CLS[m.muc_tieu]}>{MUC_TIEU_LABEL[m.muc_tieu]}</Pill></div>
        <div className="text-[11px] mt-0.5 flex gap-1 flex-wrap">{m.tao_boi==='AGENT'&&<span title="mục do máy tạo">🤖</span>}{nd&&<Pill cls={(ND_TT[nd.trang_thai]||[])[1]}>{(ND_TT[nd.trang_thai]||[])[0]} v{nd.phien_ban}{nd.tao_boi==='AGENT'?' 🤖':''}</Pill>}{m.ngay_dang?<span className="text-slate-500">{m.ngay_dang}</span>:<span className="text-slate-500">tuần {m.tuan||'?'}</span>}</div></div>; })}
      {ds.length===0&&<div className="text-[11px] text-slate-500">0 thẻ</div>}</div></div>; })}</div>
    {mo && <TheMucModal muc={mo.muc} tab0={mo.tab} onClose={()=>setMo(null)}/>}
  </div>;
}
// ----- Popup thẻ: 4 tab theo việc -----
function TheMucModal({muc, tab0, onClose}){
  const { db, me, goi, notify } = useApp(); const [tab,setTab]=useState(tab0||'noidung'); const chiXem=!laStaff(me);
  const nds=(db.noi_dung||[]).filter(n=>n.muc_id===muc.id).sort((a,b)=>a.updated_at<b.updated_at?1:-1); const nd=nds[0]||null;
  const duyetCho=nd&&(db.duyet||[]).find(d=>d.doi_tuong_id===nd.id&&d.trang_thai==='CHO'); const duyetGan=nd&&(db.duyet||[]).filter(d=>d.doi_tuong_id===nd.id).sort((a,b)=>a.created_at<b.created_at?1:-1)[0];
  const taiSan=(db.tai_san||[]).filter(t=>t.muc_id===muc.id||(nd&&t.noi_dung_id===nd.id)); const baiDang=(db.bai_dang||[]).filter(b=>b.muc_id===muc.id);
  const pTen=id=>((db.pillars||[]).find(p=>p.id===id)||{}).ten||'—';
  const tabs=[{key:'noidung',label:'✍️ Nội dung'},{key:'duyet',label:'🛂 Duyệt',count:duyetCho?1:null},{key:'sanxuat',label:'🎬 Sản xuất',count:taiSan.length||null},{key:'dang',label:'🚀 Đăng',count:baiDang.length||null}];
  const doiGd=async(gd)=>{ const ly=prompt('Lý do đổi giai đoạn tay (có audit):'); if(ly==null) return; const r=await goi('/muc/'+muc.id+'/giai-doan',{method:'POST',body:{giai_doan:gd, ly_do:ly}}); if(r.ok) notify('Đã đổi'); else notify(r.msg,'err'); };
  return <Modal open onClose={onClose} title={<span>{(DINH_DANG_ICON[muc.dinh_dang]||'📄').split(' ')[0]} {muc.tieu_de}</span>} wide>
    <div className="text-[11px] text-ink-muted mb-2 flex flex-wrap gap-x-3 gap-y-1 items-center"><span>{pTen(muc.pillar_id)}</span><Pill cls={MUC_TIEU_CLS[muc.muc_tieu]}>{MUC_TIEU_LABEL[muc.muc_tieu]}</Pill><span>giai đoạn <b>{(GIAI_DOAN.find(g=>g[0]===muc.giai_doan)||[])[1]}</b></span>{muc.tao_boi==='AGENT'&&<span>🤖 máy tạo</span>}{muc.ghi_chu&&<span className="text-ink-soft">· {muc.ghi_chu}</span>}
      {!chiXem&&<select className="ml-auto text-[11px] border border-line rounded px-1 py-0.5" value="" onChange={e=>e.target.value&&doiGd(e.target.value)}><option value="">đổi giai đoạn tay…</option>{GIAI_DOAN.map(([g,t])=><option key={g} value={g}>{t}</option>)}</select>}</div>
    <Tabs size="sm" active={tab} onChange={setTab} tabs={tabs} className="mb-3"/>
    {tab==='noidung' && <SoanNoiDung muc={muc} nd={nd} chiXem={chiXem||(nd&&nd.trang_thai==='CHO_DUYET')} onSent={()=>setTab('duyet')}/>}
    {tab==='duyet' && <DuyetTab muc={muc} nd={nd} duyetCho={duyetCho} duyetGan={duyetGan}/>}
    {tab==='sanxuat' && <SanXuatTab muc={muc} nd={nd} taiSan={taiSan} chiXem={chiXem}/>}
    {tab==='dang' && <DangTab muc={muc} nd={nd} baiDang={baiDang} taiSan={taiSan} chiXem={chiXem}/>}
  </Modal>;
}
// ----- Soạn (B4): 4 định dạng, AI viết, lưu phiên bản, gửi duyệt -----
function SoanNoiDung({muc, nd, chiXem, onSent}){
  const { db, goi, notify } = useApp();
  const trong={dinh_dang:muc.dinh_dang||'VIDEO', tieu_de:muc.tieu_de||'', hook:'', sections:[], cta:'', chi_tiet:{}, framework_id:muc.framework_id||'', san_pham_id:muc.san_pham_id||'', kenh_id:muc.kenh_id||''};
  const [f,setF]=useState(()=>nd?{...trong, ...nd, framework_id:nd.framework_id||'', san_pham_id:nd.san_pham_id||'', kenh_id:nd.kenh_id||''}:trong); useEffect(()=>{ if(nd) setF({...trong, ...nd, framework_id:nd.framework_id||'', san_pham_id:nd.san_pham_id||'', kenh_id:nd.kenh_id||''}); },[nd&&nd.id, nd&&nd.updated_at]);
  const [busy,setBusy]=useState(false); const [goc,setGoc]=useState(''); const [xemTruoc,setXemTruoc]=useState(false); const dd=f.dinh_dang;
  const set=(k,v)=>setF(o=>({...o,[k]:v})); const setSec=(i,k,v)=>setF(o=>({...o, sections:o.sections.map((s,j)=>j===i?{...s,[k]:v}:s)}));
  // ADR-009c: mức MỞ → máy ghép viết, màn hỏi lại mỗi 5 giây tới khi xong
  const choMay=async(viecId)=>{ for(let i=0;i<60;i++){ await new Promise(r=>setTimeout(r,5000)); const v=await goi('/ai/viec/'+viecId); if(!v.ok) continue; if(v.trang_thai==='XONG'&&v.noi_dung) return v; if(['HONG','HET_HAN'].includes(v.trang_thai)) return v; } return null; };
  const aiViet=async()=>{ setBusy(true); let r=await goi('/noi-dung/ai-viet',{method:'POST',body:{muc_id:muc.id, dinh_dang:dd, tieu_de:f.tieu_de, framework_id:f.framework_id, san_pham_id:f.san_pham_id, kenh_id:f.kenh_id, angle:goc}});
    if(r.ok===false&&r.cho_may&&r.viec_id){ notify('Mô hình mở trên máy ghép đang viết — chờ vài phút…'); const v=await choMay(r.viec_id); if(v&&v.noi_dung) r={ok:true, noi_dung:v.noi_dung, canh_bao:(v.ket_qua||{}).canh_bao, so_vi_du:0}; else r={ok:true, loi:v?(v.loi||'máy ghép trễ — API dự phòng sẽ làm, thử lại sau'):'quá lâu — thử lại sau'}; }
    setBusy(false);
    if(!r.ok) return notify(r.msg,'err'); if(r.ok&&r.loi) return notify(r.loi+(r.thieu_key?' — cắm ANTHROPIC_API_KEY (secret Worker)':''),'err');
    const n=r.noi_dung; setF(o=>({...o, tieu_de:n.tieu_de||o.tieu_de, hook:n.hook, sections:n.sections, cta:n.cta, chi_tiet:{...o.chi_tiet, ...n.chi_tiet}})); notify('AI đã viết'+(r.so_vi_du?(' (học từ '+r.so_vi_du+' bài đã duyệt)'):'')+(r.canh_bao&&r.canh_bao.length?(' · cân nhắc: '+r.canh_bao.map(c=>c.cum_tu).join(', ')):''), r.canh_bao&&r.canh_bao.length?'warn':'ok'); };
  const luu=async()=>{ setBusy(true); const body={muc_id:muc.id, dinh_dang:dd, tieu_de:f.tieu_de, hook:f.hook, sections:f.sections, cta:f.cta, chi_tiet:f.chi_tiet, framework_id:f.framework_id||null, san_pham_id:f.san_pham_id||null, kenh_id:f.kenh_id||null}; const r=await goi(nd?('/noi-dung/'+nd.id):'/noi-dung',{method:nd?'PATCH':'POST',body}); setBusy(false); if(r.ok) notify('Đã lưu'+(nd?(' (phiên bản mới)'):'')); else notify(r.msg,'err'); return r.ok?(nd?nd.id:r.id):null; };
  const gui=async()=>{ const id=await luu(); if(!id) return; setBusy(true); const r=await goi('/noi-dung/'+id+'/gui-duyet',{method:'POST'}); setBusy(false); if(r.ok){ notify(r.tu_tra_lai?('Máy trả lại (B5): '+r.cham.loi_cung.join('; ')):('Đã gửi duyệt · máy chấm '+r.cham.diem+'/100'), r.tu_tra_lai?'warn':'ok'); onSent&&onSent(); } else notify(r.msg,'err'); };
  const Sel=({k,l,ds,ten})=><Field label={l} className="!mb-2"><Select className="!py-1.5 text-xs" value={f[k]} onChange={e=>set(k,e.target.value)} disabled={chiXem}><option value="">—</option>{ds.map(x=><option key={x.id} value={x.id}>{ten?ten(x):x.ten}</option>)}</Select></Field>;
  const nhanSec = dd==='VIDEO'?'Cảnh':dd==='CAROUSEL'?'Slide':'Đoạn';
  return <div className="space-y-3">
    <div className="flex items-center justify-between gap-2 flex-wrap"><div className="flex items-center gap-2"><Pill cls="bg-brand-bg text-brand-dark">{DINH_DANG_ICON[dd]}</Pill>{nd&&<Pill cls={(ND_TT[nd.trang_thai]||[])[1]}>{(ND_TT[nd.trang_thai]||[])[0]} · v{nd.phien_ban} · {nd.created_by_name}{nd.tao_boi==='AGENT'?' 🤖':''}</Pill>}{nd&&nd.ly_do_may&&<span className="text-[11px] text-ink-muted">🤖 {nd.ly_do_may}</span>}</div>
      {!chiXem&&<div className="flex gap-2 flex-wrap"><Btn variant="ghost" onClick={()=>setXemTruoc(!xemTruoc)}>{xemTruoc?'✏️ Sửa':'👁 Xem bản đăng'}</Btn><Btn variant="ghost" onClick={luu} disabled={busy}>💾 Lưu</Btn><Btn variant="brand" onClick={gui} disabled={busy||(!nd&&!f.hook&&!f.tieu_de)}>📤 Gửi duyệt (G3)</Btn></div>}</div>
    {chiXem&&nd&&nd.trang_thai==='CHO_DUYET'&&<Callout tone="warn">Bài đang chờ duyệt — muốn sửa thì nhờ người duyệt trả lại.</Callout>}
    {xemTruoc ? <Card pad="p-3"><div className="text-[11px] text-ink-muted mb-1">Bản đăng cuối ({DINH_DANG_ICON[dd]})</div><pre className="whitespace-pre-wrap text-sm text-ink font-sans">{banDangFE(f)}</pre></Card> : <>
      <div className="grid sm:grid-cols-3 gap-x-2"><Sel k="framework_id" l="Framework" ds={(db.frameworks||[]).filter(x=>x.active)}/><Sel k="san_pham_id" l="Sản phẩm (thông số thật)" ds={(db.san_pham||[]).filter(x=>x.active)} ten={s=>(s.ma?s.ma+' · ':'')+s.ten}/><Sel k="kenh_id" l="Kênh" ds={(db.kenh||[]).filter(x=>x.active)}/></div>
      {!chiXem&&<div className="flex gap-2 items-end"><Field label="Góc nhìn cho AI (tuỳ chọn)" className="!mb-0 flex-1"><Input className="!py-1.5 text-xs" value={goc} onChange={e=>setGoc(e.target.value)} placeholder="VD: nói từ góc thợ ốp lát, mở bằng vết ố thật"/></Field><Btn variant="soft" onClick={aiViet} disabled={busy}>{busy?'…':'✨ AI viết'}</Btn></div>}
      <Field label="Tiêu đề" className="!mb-2"><Input className="!py-1.5" value={f.tieu_de} onChange={e=>set('tieu_de',e.target.value)} disabled={chiXem}/></Field>
      <Field label={dd==='ANH'?'Headline (≤ 8 từ)':dd==='CAROUSEL'?'Slide bìa':dd==='POST'?'Câu mở (hook)':'Hook 3 giây đầu'} className="!mb-2"><Textarea rows="2" value={f.hook} onChange={e=>set('hook',e.target.value)} disabled={chiXem}/></Field>
      {dd!=='ANH' && <div className="space-y-1.5"><div className="text-[13px] font-semibold text-ink">{nhanSec}</div>{f.sections.map((s,i)=><div key={i} className="grid grid-cols-[80px_1fr_auto] gap-1.5 items-start"><Input className="!py-1 text-xs" value={s.label} onChange={e=>setSec(i,'label',e.target.value)} disabled={chiXem}/><div className="space-y-1"><Textarea rows="2" className="!py-1 text-xs" value={s.text} onChange={e=>setSec(i,'text',e.target.value)} disabled={chiXem} placeholder={dd==='VIDEO'?'lời bình':'nội dung'}/>{dd!=='POST'&&<Input className="!py-1 text-[11px]" value={s.hinh||''} onChange={e=>setSec(i,'hinh',e.target.value)} disabled={chiXem} placeholder="gợi ý hình"/>}</div>{!chiXem&&<button onClick={()=>setF(o=>({...o,sections:o.sections.filter((_,j)=>j!==i)}))} className="text-rose-400 text-xs px-1">✕</button>}</div>)}
        {!chiXem&&<LinkBtn onClick={()=>setF(o=>({...o,sections:[...o.sections,{label:nhanSec+' '+(o.sections.length+1),text:'',hinh:''}]}))}>＋ thêm {nhanSec.toLowerCase()}</LinkBtn>}</div>}
      <Field label={dd==='ANH'?'Nút CTA (≤ 4 từ)':dd==='CAROUSEL'?'Slide chốt (CTA)':'CTA'} className="!mb-2"><Input className="!py-1.5" value={f.cta} onChange={e=>set('cta',e.target.value)} disabled={chiXem}/></Field>
      {(CT_KEYS[dd]||[]).map(([k,l])=><Field key={k} label={l} className="!mb-2"><Textarea rows={k==='brief'||k==='caption'?3:1} className="!py-1.5 text-xs" value={f.chi_tiet[k]||''} onChange={e=>set('chi_tiet',{...f.chi_tiet,[k]:e.target.value})} disabled={chiXem}/></Field>)}
      {dd==='VIDEO'&&f.chi_tiet.video_url&&<div className={CALLOUT.ok}>🎬 Đã gắn video dựng: <a className="underline" href={f.chi_tiet.video_url} target="_blank" rel="noreferrer">{f.chi_tiet.video_url}</a></div>}
    </>}
  </div>;
}
// ----- Duyệt G3 (B5 máy chấm sẵn, người quyết) -----
function DuyetTab({muc, nd, duyetCho, duyetGan}){
  const { db, me, goi, notify } = useApp(); const [ly,setLy]=useState(''); const [busy,setBusy]=useState(false);
  const chanTuDuyet=((db.module_config||{}).duyet||{}).chan_tu_duyet!==false; const cm=(duyetCho||duyetGan||{}).cham_may||{};
  const quyet=async(q)=>{ if(q==='TRA_LAI'&&!ly.trim()) return notify('Ghi lý do trả lại — máy học từ đây','err'); setBusy(true); const r=await goi('/duyet/'+duyetCho.id+'/quyet',{method:'POST',body:{quyet:q, ly_do:ly}}); setBusy(false); if(r.ok) notify(q==='DUYET'?'Đã duyệt → Sản xuất':'Đã trả lại → Soạn'); else notify(r.msg,'err'); };
  const lichSu=nd?(db.duyet||[]).filter(d=>d.doi_tuong_id===nd.id).sort((a,b)=>a.created_at<b.created_at?1:-1):[];
  if(!nd) return <Empty>Chưa có nội dung để duyệt — soạn ở tab Nội dung trước.</Empty>;
  return <div className="space-y-3">
    <Card pad="p-3"><div className="flex items-center gap-3"><div className={"font-display text-3xl font-extrabold "+((cm.diem||0)>=70?'text-emerald-600':(cm.diem||0)>=40?'text-amber-600':'text-rose-500')}>{cm.diem??'—'}</div><div className="text-xs"><div className="font-semibold text-ink">Máy thẩm định (B5) — luật cứng + luật mềm, không dùng AI</div>{(cm.loi_cung||[]).length>0&&<div className="text-rose-700">⚠ {cm.loi_cung.join(' · ')}</div>}{(cm.ly_do||[]).length>0&&<div className="text-ink-muted">{cm.ly_do.join(' · ')}</div>}{!cm.diem&&cm.diem!==0&&<div className="text-ink-muted">Chưa gửi duyệt nên chưa chấm.</div>}</div></div></Card>
    <Card pad="p-3"><div className="text-[11px] text-ink-muted mb-1">Bản đăng cuối ({DINH_DANG_ICON[nd.dinh_dang]}) · v{nd.phien_ban} · {nd.created_by_name}</div><pre className="whitespace-pre-wrap text-sm text-ink font-sans max-h-72 overflow-auto">{banDangFE(nd)}</pre>{nd.dinh_dang==='VIDEO'&&(nd.sections||[]).some(s=>s.hinh)&&<div className="text-[11px] text-ink-muted mt-1">Hình: {(nd.sections||[]).map(s=>s.hinh).filter(Boolean).join(' · ')}</div>}</Card>
    {duyetCho ? (laGat(me) ? (chanTuDuyet&&duyetCho.nguoi_gui_id===me.id ? <Callout tone="warn">Bài do chính bạn gửi — người khác duyệt (luật người lập ≠ người duyệt).</Callout>
      : <div className="space-y-2"><Textarea rows="2" placeholder="Lý do (bắt buộc khi trả lại — máy học từ đây)" value={ly} onChange={e=>setLy(e.target.value)}/><div className="flex gap-2 justify-end"><Btn variant="ghost" onClick={()=>quyet('TRA_LAI')} disabled={busy}>↩ Trả lại</Btn><Btn variant="ok" onClick={()=>quyet('DUYET')} disabled={busy}>✅ Duyệt → Sản xuất</Btn></div></div>)
      : <Callout tone="info">Đang chờ Trưởng MKT / Admin duyệt (gửi {fmtDate(duyetCho.created_at)}).</Callout>)
      : <Callout tone="note">{nd.trang_thai==='DUYET'?'Bài đã duyệt.':nd.trang_thai==='TRA_LAI'?'Bài bị trả lại — sửa ở tab Nội dung rồi gửi lại.':'Bài chưa gửi duyệt.'}</Callout>}
    {lichSu.length>0&&<div className="text-[11px] text-ink-muted"><div className="font-semibold mb-0.5">Lịch sử duyệt</div>{lichSu.map(d=><div key={d.id} className="py-0.5 border-t border-line">{d.trang_thai==='CHO'?'⏳ chờ':d.trang_thai==='DUYET'?'✓ duyệt':'↩ trả lại'} · gửi {d.nguoi_gui_ten} {fmtDate(d.created_at)}{d.quyet_boi?(' · '+d.quyet_boi+' '+fmtDate(d.quyet_at)):''}{d.ly_do_nguoi?(' · '+d.ly_do_nguoi):''} · máy {(d.cham_may||{}).diem}/100</div>)}</div>}
  </div>;
}
// ADR-014a — dòng thời gian máy đọc từng giây (qwen2.5vl): màu theo bước thi công, độ đậm theo thẩm mỹ; rê chuột xem chi tiết
const dongThoiGian=t=>{ try{ const p=typeof t.phan_tich==='string'?JSON.parse(t.phan_tich||'{}'):(t.phan_tich||{}); return Array.isArray(p&&p.timeline)?p.timeline:[]; }catch(e){ return []; } };
const mauBuoc=b=>{ let h=0; for(const c of String(b||'')) h=(h*31+c.charCodeAt(0))>>>0; return 'hsl('+(h%360)+' 55% 48%)'; };
function DaiThoiGian({t}){ const tl=dongThoiGian(t); if(!tl.length) return null; const het=tl[tl.length-1].den||1;
  return <div className="mt-1"><div className="flex h-2 rounded overflow-hidden bg-slate-100" role="img" aria-label={tl.map(d=>d.nhom?tenNhom(d.nhom):d.buoc).join(', ')}>{tl.map((d,i)=><div key={i} style={{width:((d.den-d.tu)/het*100)+'%', background:d.nhom?((NHOM_HINH.find(n=>n.k===d.nhom)||{}).mau||'#94a3b8'):mauBuoc(d.buoc), opacity:d.nguoi?1:0.55, outline:d.can_xac_nhan?'1px dashed #b91c1c':'none', outlineOffset:'-1px'}} title={d.tu+'–'+d.den+'s · '+(d.nhom?tenNhom(d.nhom)+' · ':'')+(d.buoc||d.bai_test||'')+(d.nguoi?' · người đã xác nhận':d.can_xac_nhan?' · máy chưa chắc, gán ở Bộ não AI › Nhãn hình':'')+' · '+(d.hanh_dong||'')+' · '+(d.vat_lieu||'')+' · '+(d.co_canh||'')+' · thẩm mỹ '+d.tham_my+'/10 · nét '+d.ro_net+'/10'+(d.mo_ta?(' · '+d.mo_ta):'')}/>)}</div>
    <div className="text-[10.5px] text-ink-muted truncate" title={[...new Set(tl.map(d=>d.buoc||tenNhom(d.nhom)))].join(' → ')}>{[...new Set(tl.map(d=>d.buoc||(d.nhom?tenNhom(d.nhom):'')))].filter(Boolean).join(' → ')}{tl.some(d=>d.can_xac_nhan)?' · '+tl.filter(d=>d.can_xac_nhan).length+' đoạn chờ người xác nhận':''}</div></div>; }
// ----- Sản xuất: tài sản (upload/link) + Lọc/Dựng video popup -----
function SanXuatTab({muc, nd, taiSan, chiXem}){
  const { db, me, goi, notify, refresh } = useApp(); const [link,setLink]=useState(''); const [busy,setBusy]=useState(false); const [tool,setTool]=useState(null); const fileRef=useRef(null); const [mayChon,setMayChon]=useState('');
  const upload=async(file)=>{ if(!file) return; setBusy(true); try{ const tok=localStorage.getItem('kingsmen_os_token'); const r=await fetch('/api/tai-san/upload?type='+encodeURIComponent(file.type||'application/octet-stream'),{method:'POST',headers:{Authorization:'Bearer '+tok,'Content-Type':file.type||'application/octet-stream'},body:file}); const j=await r.json(); if(!r.ok) throw new Error(j.error||'Lỗi tải lên');
      const x=await goi('/tai-san',{method:'POST',body:{ten:file.name, media_url:j.media_url, media_type:j.media_type, loai:j.media_type==='IMAGE'?'ANH':j.media_type==='AUDIO'?'NHAC':j.media_type==='FILE'?'KHAC':'FOOTAGE', muc_id:muc.id, noi_dung_id:nd&&nd.id}}); if(x.ok) notify('Đã thêm tài sản'); else notify(x.msg,'err'); }catch(e){ notify(e.message,'err'); } setBusy(false); };
  const laAnhLink=l=>/\.(jpe?g|png|webp|gif)(\?|$)/i.test(l);
  const themLink=async()=>{ if(!link.trim()) return; if(/drive\.google\.com\/drive\/(u\/\d+\/)?folders\//.test(link)){ const n=prompt('Đây là THƯ MỤC Drive — app sẽ cho máy dựng tải clip trong thư mục về kho. Nạp tối đa bao nhiêu file? (rải đều theo tên, bỏ file đã nạp)','8'); if(n===null) return; setBusy(true); const r=await goi('/muc/'+muc.id+'/nap-drive',{method:'POST',body:{link:link.trim(), toi_da:Number(n)||8, may_id:mayChon||undefined}}); setBusy(false); if(r.ok){ notify((r.trung?'Máy đang nạp rồi':'Đã giao '+r.may_ten+' nạp tối đa '+r.toi_da+' file')+' — footage hiện dần ở dưới'); setLink(''); } else notify(r.msg,'err'); return; } setBusy(true); const x=await goi('/tai-san',{method:'POST',body:{ten:link.split('/').pop().slice(0,60), media_url:link.trim(), media_type:laAnhLink(link)?'IMAGE':'VIDEO', loai:laAnhLink(link)?'ANH':'FOOTAGE', muc_id:muc.id, noi_dung_id:nd&&nd.id}}); setBusy(false); if(x.ok){ notify('Đã thêm'); setLink(''); } else notify(x.msg,'err'); };
  const xoa=async(t)=>{ if(!confirm('Xoá tài sản "'+t.ten+'"?')) return; const r=await goi('/tai-san/'+t.id,{method:'DELETE'}); if(r.ok) notify('Đã xoá'); else notify(r.msg,'err'); };
  const moTool=(mode)=>{ if(nd&&nd.dinh_dang==='VIDEO'){ try{ localStorage.setItem('kingsmen_kichban_dung', JSON.stringify({script_id:nd.id, tieu_de:nd.tieu_de||nd.hook, text:[nd.hook,...(nd.sections||[]).map(s=>(s.label?s.label+': ':'')+s.text),nd.cta].filter(Boolean).join('\n'), san_pham_id:nd.san_pham_id||null, kenh_id:nd.kenh_id||null, luc:Date.now()})); }catch(e){} } setTool(mode); };
  useEffect(()=>{ const h=e=>{ if(e.data&&e.data.type==='KINGSMEN_VIDEO_GAN') refresh(); }; window.addEventListener('message',h); return ()=>window.removeEventListener('message',h); },[]);
  // ADR-008: dựng trên máy ghép — máy của tôi trước, rồi máy khác đang bật, rồi Trạm văn phòng
  const mays=(db.may_ghep||[]).filter(m=>(m.kha_nang||[]).includes('dung_video')).sort((a,b)=>((a.chu_user_id===me.id)?-1:0)-((b.chu_user_id===me.id)?-1:0)); const tramSong=!!((db.tram||{}).trang_thai||{}).song;
  const lenhDung=((db.tram||{}).lenh||[]).filter(l=>nd&&((l.viec==='dung_video'&&l.tham_so.noi_dung_id===nd.id)||(l.viec==='chay_agent'&&l.tham_so.viec==='dung_video'))).slice(0,3); const mayTen=id=>id==='tram'?'Trạm văn phòng':((mays.find(m=>m.id===id)||{}).ten||id||'—');
  const dung=async()=>{ setBusy(true); const r=await goi('/noi-dung/'+nd.id+'/dung',{method:'POST',body:{may_id:mayChon&&mayChon!=='tram'?mayChon:undefined}}); setBusy(false); if(r.ok) notify(r.trung?('Máy '+r.may_ten+' đã có lệnh này rồi'):('Đã giao máy '+r.may_ten+(r.ly_do?(' — '+r.ly_do):' — máy lấy trong ~30 giây'))); else notify(r.msg,'err'); };
  const ct=(nd&&nd.chi_tiet)||{}; const coMay=mays.some(m=>m.song)||tramSong;
  return <div className="space-y-3">
    <Callout tone="info">{muc.dinh_dang==='VIDEO'?<>Video (B8 người quyết): máy chọn footage theo gợi ý hình từng cảnh, đọc lời bình bằng giọng Google{db.san_sang.tts?'':' (chưa cắm GOOGLE_TTS_KEY nên bản nháp không tiếng)'}, trộn nhạc nền, in phụ đề, xuất <b>bản nháp</b> + <b>gói CapCut</b> để dựng sâu. Người xem, chỉnh, gắn bản cuối rồi qua tab Đăng.</>:muc.dinh_dang==='ANH'?<>Ảnh: designer làm theo brief trong nội dung; tải ảnh lên đây rồi qua tab Đăng.</>:<>Post/Carousel: bản đăng cuối lấy từ nội dung đã duyệt; thêm ảnh minh hoạ nếu cần rồi qua tab Đăng.</>}{nd&&nd.trang_thai!=='DUYET'&&<b> Nội dung chưa duyệt (G3) — sản xuất sau khi duyệt.</b>}</Callout>
    {!chiXem&&<div className="flex gap-2 flex-wrap items-center"><input ref={fileRef} type="file" accept="image/*,video/*,audio/*" className="hidden" onChange={e=>upload(e.target.files[0])}/><Btn variant="ghost" onClick={()=>fileRef.current.click()} disabled={busy||!db.san_sang.media} title={db.san_sang.media?'':'Chưa cấu hình R2 MEDIA — dán link'}>⬆ Tải ảnh/video/nhạc</Btn><Input className="!w-56 !py-1.5 text-xs" placeholder="hoặc dán link Drive/ảnh" value={link} onChange={e=>setLink(e.target.value)}/><Btn variant="ghost" onClick={themLink} disabled={busy||!link.trim()}>＋ Thêm link</Btn>{/drive\.google\.com\/drive\/(u\/\d+\/)?folders\//.test(link)&&<Btn variant="brand" onClick={async()=>{ const n=prompt('Nạp tối đa bao nhiêu clip/ảnh từ thư mục này? (máy rải đều theo thứ tự tên, bỏ file đã nạp)','8'); if(n===null) return; setBusy(true); const r=await goi('/muc/'+muc.id+'/nap-drive',{method:'POST',body:{link:link.trim(), toi_da:Number(n)||8, may_id:mayChon||undefined}}); setBusy(false); if(r.ok){ notify((r.trung?'Máy đang nạp rồi':'Đã giao '+r.may_ten+' nạp tối đa '+r.toi_da+' file')+' — footage hiện dần ở dưới, Claude tự viết mô tả từng clip'); setLink(''); } else notify(r.msg,'err'); }} disabled={busy} title="Máy dựng tự tải clip từ thư mục Drive (để “ai có link cũng xem”), nén 1080×1920, tải lên kho; Claude nhìn khung hình viết mô tả để chọn cảnh">📥 Nạp từ Drive</Btn>}{taiSan.some(t=>t.loai==='FOOTAGE'&&t.media_type==='VIDEO'&&!t.phan_tich)&&<Btn variant="soft" onClick={async()=>{ setBusy(true); const r=await goi('/muc/'+muc.id+'/phan-tich',{method:'POST'}); setBusy(false); if(r.ok) notify(r.trung?('Máy '+r.may_ten+' đã có lệnh phân tích'):('Máy '+r.may_ten+' đang phân tích '+r.so_clip+' clip (đoạn nét/động/sáng + cỡ cảnh)')); else notify(r.msg,'err'); }} disabled={busy} title="Footage nạp trước ADR-010 chưa có phân tích đoạn — máy dựng cần nó để ghép nhiều shot và chọn đoạn đẹp">🔬 Phân tích footage</Btn>}{taiSan.some(t=>t.loai==='FOOTAGE'&&t.media_type==='VIDEO')&&<Btn variant="soft" onClick={async()=>{ setBusy(true); const r=await goi('/muc/'+muc.id+'/doc-khung',{method:'POST',body:{lai:taiSan.every(t=>t.loai!=='FOOTAGE'||t.media_type!=='VIDEO'||dongThoiGian(t).length>0)}}); setBusy(false); if(r.ok) notify(r.trung?'Máy học đã có lệnh đọc':'Máy học đang đọc từng giây footage (qwen2.5vl, khoảng 1 phút mỗi clip 20 giây)'); else notify(r.msg,'err'); }} disabled={busy} title="Máy học đọc từng giây: bước thi công, hành động, vật liệu, cỡ cảnh, thẩm mỹ hoàn thiện — để chọn đúng đoạn cho từng câu lời thoại">🧠 Đọc từng giây</Btn>}
      {muc.dinh_dang==='VIDEO'&&<><Btn variant="soft" onClick={()=>moTool('loc')}>🎞 Lọc footage</Btn><Btn variant="soft" onClick={async()=>{ setBusy(true); const r=await goi('/noi-dung/'+nd.id+'/loc',{method:'POST'}); setBusy(false); if(r.ok) notify(r.trung?'Máy đang lọc rồi':('Đã giao máy lọc '+r.so_footage+' footage — đoạn đề xuất về sau vài phút')); else notify(r.msg,'err'); }} disabled={busy||!nd||!taiSan.some(t=>t.loai==='FOOTAGE'&&t.media_type==='VIDEO')} title="Máy ghép nghe lời (Whisper) + nhìn (CLIP) cắt đoạn hợp từng cảnh">🤖 Máy lọc footage</Btn><Btn variant="ghost" onClick={()=>moTool('dung')} disabled={!nd||nd.trang_thai!=='DUYET'} title="Dựng nhanh trong trình duyệt">✂️ Dựng tay</Btn></>}</div>}
    {!chiXem&&muc.dinh_dang==='VIDEO'&&nd&&nd.trang_thai==='DUYET'&&<Card pad="p-3"><div className="flex items-center gap-2 flex-wrap"><SectionTitle>🎬 Dựng video nháp trên máy</SectionTitle>
      <Select className="!w-64 !py-1.5 text-xs" value={mayChon} onChange={e=>setMayChon(e.target.value)}><option value="">— máy đang bật (ưu tiên máy của tôi) —</option>{mays.map(m=><option key={m.id} value={m.id}>{m.song?'🟢':'⚪'} {m.ten} · {m.chu_ten}{m.song?'':' (im)'}</option>)}{tramSong&&<option value="tram">🟢 Trạm văn phòng</option>}</Select>
      <Btn variant="brand" className="!py-1.5 text-xs" onClick={dung} disabled={busy||(!coMay&&!mayChon)} title={!coMay?'Không có máy nào đang bật — ghép máy ở Hồ sơ › Máy dựng':''}>🎬 Dựng ngay</Btn>
      <span className="text-[11px] text-ink-muted">Footage/ảnh của thẻ: {taiSan.filter(t=>['FOOTAGE','ANH'].includes(t.loai)).length} · máy đang bật: {mays.filter(m=>m.song).length}{tramSong?' + Trạm':''}{!mays.length&&<> · <b>chưa có máy ghép</b> (Hồ sơ › Máy dựng)</>}</span></div>
      {lenhDung.length>0&&<div className="mt-2 text-[11px] space-y-0.5">{lenhDung.map(l=><div key={l.id} className="flex gap-2 items-center"><Pill cls={l.trang_thai==='XONG'?'bg-emerald-100 text-emerald-800':l.trang_thai==='HONG'?'bg-rose-100 text-rose-700':l.trang_thai==='DA_GUI'?'bg-sky-100 text-sky-800':'bg-slate-100 text-ink'}>{l.trang_thai==='CHO'?'chờ máy lấy':l.trang_thai==='DA_GUI'?'máy đang dựng':l.trang_thai}</Pill><span className="text-ink">{mayTen(l.may_id)}</span><span className="text-ink-muted truncate">{l.ket_qua||''}</span><span className="text-slate-500 shrink-0">{fmtDate(l.created_at)}</span></div>)}</div>}
      {ct.canh_chon&&<ChamCanh ct={ct} taiSan={taiSan}/>}
      {ct.video_url&&<ChinhGhep nd={nd} taiSan={taiSan} mays={mays} mayChon={mayChon}/>}
      {ct.loc_de_xuat&&<ChamLoc ct={ct} taiSan={taiSan}/>}
      {ct.tts_mo_url&&<ChamGiongMo ct={ct}/>}
      {ct.video_url&&<div className={CALLOUT.ok+' mt-2 text-xs'}>🎬 Bản nháp mới nhất: <a className="underline" href={ct.video_url} target="_blank" rel="noreferrer">xem</a>{ct.goi_dung_url&&<> · 📦 <a className="underline font-semibold" href={ct.goi_dung_url} download>Tải gói CapCut</a> (từng cảnh + giọng + SRT + nhạc)</>}{ct.thieu_hinh&&<div className="text-amber-700 mt-1">⚠ Thiếu hình: {ct.thieu_hinh} — tải footage đúng cảnh rồi dựng lại</div>}</div>}
    </Card>}
    {taiSan.length===0?<Empty>Chưa có tài sản nào cho thẻ này.</Empty>:<div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{taiSan.map(t=><div key={t.id} className="rounded-xl border border-line overflow-hidden bg-white"><div className="aspect-video bg-slate-100 grid place-items-center overflow-hidden">{t.media_type==='IMAGE'?<img src={t.media_url} alt="" className="w-full h-full object-cover"/>:<span className="text-2xl">{t.media_type==='AUDIO'?'🎵':t.media_type==='FILE'?'📦':t.loai==='VIDEO_XUAT'?'🎬':'🎞'}</span>}</div><div className="p-1.5 text-[11px]"><div className="font-semibold text-ink truncate" title={t.mo_ta||t.ten}>{t.ten}</div><DaiThoiGian t={t}/><div className="text-ink-muted">{t.loai} · {t.created_by_name}</div><div className="flex gap-2 mt-0.5"><a className="text-brand-dark hover:underline" href={t.media_url} target="_blank" rel="noreferrer" download={t.media_type==='FILE'?true:undefined}>{t.media_type==='FILE'?'tải':'mở'}</a>{!chiXem&&<LinkBtn tone="danger" onClick={()=>xoa(t)}>xoá</LinkBtn>}</div></div></div>)}</div>}
    {tool && <div className="fixed inset-0 z-50 bg-ink/70 flex flex-col"><div className="bg-ink text-white px-3 py-2 flex items-center justify-between text-sm"><span>🎬 Công cụ {tool==='dung'?'Dựng':'Lọc'} video — {nd?(nd.tieu_de||nd.hook):muc.tieu_de}</span><button onClick={()=>{ setTool(null); refresh(); }} className="px-3 py-1 rounded-lg bg-white/10 hover:bg-white/20">Đóng ✕</button></div><iframe title="tool" src={'/tools/loc-video.html?mode='+tool} className="flex-1 w-full bg-white"/></div>}
  </div>;
}
// ADR-010a — CHỈNH GHÉP: người sửa kế hoạch ghép máy lập (clip nào, giây vào/ra, thứ tự, thêm/bớt shot) → "Dựng lại" → app so máy↔người
// thành mẫu học (chon_canh · chon_doan · ghep_canh) rồi giao máy dựng đúng bản người. Cắt bằng giây, không kéo thả — 375 vẫn dùng được.
function ChinhGhep({nd, taiSan, mays, mayChon}){
  const { goi, notify } = useApp(); const [mo,setMo]=useState(false); const [ds,setDs]=useState(null); const [canh,setCanh]=useState([]); const [busy,setBusy]=useState(false); const [nguon,setNguon]=useState('');
  const clips=taiSan.filter(t=>['FOOTAGE','ANH'].includes(t.loai)); const ten=id=>((clips.find(t=>t.id===id)||{}).ten)||id||'—'; const giay=id=>((clips.find(t=>t.id===id)||{}).giay)||null;
  const tai=async()=>{ setBusy(true); const r=await goi('/noi-dung/'+nd.id+'/ghep'); setBusy(false); if(!r.ok) return notify(r.msg,'err'); const g=(r.ghep||[])[0]; setDs(r.ghep||[]); setCanh(g?g.canh.map(c=>({...c, shots:c.shots.map(x=>({...x}))})):[]); setNguon(g?(g.nguon==='MAY'?'máy lập':'người chỉnh '+(g.created_by_name||'')):''); };
  const moRa=()=>{ setMo(true); if(ds===null) tai(); };
  const sua=(k,i,p)=>setCanh(canh.map(c=>c.k!==k?c:{...c, shots:c.shots.map((x,j)=>j!==i?x:{...x,...p})}));
  const them=k=>setCanh(canh.map(c=>{ if(c.k!==k) return c; const cuoi=c.shots[c.shots.length-1]||{tai_san_id:(clips[0]||{}).id,tu:0,den:2}; const con=Math.max(0.8,+(c.d-c.shots.reduce((a,x)=>a+(x.den-x.tu),0)).toFixed(2)); return {...c, shots:[...c.shots,{tai_san_id:cuoi.tai_san_id, tu:cuoi.den, den:+(cuoi.den+Math.min(con,3)).toFixed(2)}]}; }));
  const bo=(k,i)=>setCanh(canh.map(c=>c.k!==k?c:{...c, shots:c.shots.filter((x,j)=>j!==i)}));
  const doi=(k,i,d)=>setCanh(canh.map(c=>{ if(c.k!==k) return c; const a=c.shots.slice(); const j=i+d; if(j<0||j>=a.length) return c; [a[i],a[j]]=[a[j],a[i]]; return {...c, shots:a}; }));
  const tongShot=c=>c.shots.reduce((a,x)=>a+Math.max(0,(+x.den||0)-(+x.tu||0)),0);
  const dungLai=async()=>{ for(const c of canh){ if(!c.shots.length) return notify('Cảnh "'+c.label+'" chưa có shot nào','err'); for(const x of c.shots){ if(!x.tai_san_id) return notify('Cảnh "'+c.label+'": shot chưa chọn clip','err'); if(!(+x.den>+x.tu)) return notify('Cảnh "'+c.label+'": giây ra phải lớn hơn giây vào','err'); } }
    setBusy(true); const r=await goi('/noi-dung/'+nd.id+'/ghep',{method:'POST',body:{canh, may_id:mayChon&&mayChon!=='tram'?mayChon:undefined}}); setBusy(false); if(!r.ok) return notify(r.msg,'err'); notify('Đã lưu bản ghép của bạn ('+r.so_mau+' mẫu máy học)'+(r.dung?' — máy đang dựng lại':' — chưa có máy dựng đang bật, dựng sau')); setDs(null); setMo(false); };
  return <div className="mt-2 rounded-xl border border-line p-2 text-[11px]">
    <div className="flex items-center gap-2 flex-wrap"><span className="font-semibold text-ink">✂️ Chỉnh ghép (clip nào · giây vào/ra · thứ tự) — máy học từ mỗi lần bạn sửa</span><Btn variant="ghost" className="!py-0.5 !px-2 text-[11px]" onClick={()=>mo?setMo(false):moRa()}>{mo?'Đóng':'Mở bản ghép'}</Btn>{nguon&&<span className="text-ink-muted">bản hiện tại: {nguon}</span>}</div>
    {mo&&(ds===null?<div className="text-ink-muted mt-1">Đang tải…</div>:!canh.length?<div className="text-amber-700 mt-1">Chưa có kế hoạch ghép — máy dựng bản cũ chưa ghi shot. Bấm 🎬 Dựng ngay một lần (máy con bản 1.2) rồi mở lại.</div>:<div className="mt-1 space-y-1.5">
      {canh.map(c=><div key={c.k} className="rounded-lg border border-line/70 p-1.5"><div className="flex items-center gap-2 flex-wrap"><span className="font-semibold text-ink">{c.k+1}. {c.label}</span><span className="text-ink-muted truncate max-w-[260px]" title={c.text}>{c.text}</span><span className={"ml-auto "+(Math.abs(tongShot(c)-c.d)>0.5?'text-amber-700':'text-ink-muted')}>shot {tongShot(c).toFixed(1)}s / lời {c.d.toFixed(1)}s</span></div>
        {c.hinh&&<div className="text-ink-muted">💡 {c.hinh}</div>}
        {c.shots.map((x,i)=><div key={i} className="flex items-center gap-1 flex-wrap mt-1"><span className="text-ink-muted w-4">{i+1}</span>
          <Select className="!py-0.5 !px-1 text-[11px] !w-48" value={x.tai_san_id||''} onChange={e=>sua(c.k,i,{tai_san_id:e.target.value})}><option value="">— clip —</option>{clips.map(t=><option key={t.id} value={t.id}>{t.ten}{t.giay?' ('+t.giay+'s)':''}</option>)}</Select>
          <span className="text-ink-muted">vào</span><Input type="number" step="0.1" min="0" className="!py-0.5 !px-1 text-[11px] !w-16" value={x.tu} onChange={e=>sua(c.k,i,{tu:+e.target.value})}/><span className="text-ink-muted">ra</span><Input type="number" step="0.1" min="0" className="!py-0.5 !px-1 text-[11px] !w-16" value={x.den} onChange={e=>sua(c.k,i,{den:+e.target.value})}/><span className="text-ink-muted">{giay(x.tai_san_id)?'/ '+giay(x.tai_san_id)+'s':''}</span>
          <button className="px-1 text-ink-muted hover:text-ink" title="lên" onClick={()=>doi(c.k,i,-1)}>↑</button><button className="px-1 text-ink-muted hover:text-ink" title="xuống" onClick={()=>doi(c.k,i,1)}>↓</button><button className="px-1 text-rose-600" title="bỏ shot" onClick={()=>bo(c.k,i)}>✕</button></div>)}
        <button className="mt-1 text-brand font-semibold" onClick={()=>them(c.k)}>+ thêm shot</button></div>)}
      <div className="flex gap-2 items-center flex-wrap"><Btn variant="brand" className="!py-1 text-xs" onClick={dungLai} disabled={busy}>🎬 Dựng lại theo bản chỉnh</Btn><Btn variant="ghost" className="!py-1 text-xs" onClick={tai} disabled={busy}>↺ Bỏ sửa</Btn><span className="text-ink-muted">Mỗi lần dựng lại: máy ghi mẫu chọn cảnh / chọn đoạn / độ dài shot từ chỗ bạn sửa; đủ mẫu thì Máy › Bộ não AI › Huấn luyện.</span></div>
    </div>)}
  </div>;
}
// ADR-009 — người chấm cảnh máy chọn → nhãn huấn luyện đầu nhìn (chon_canh)
function ChamCanh({ct, taiSan}){
  const { goi, notify } = useApp(); const [busy,setBusy]=useState(false); const [chon,setChon]=useState({}); let ds=[]; try{ ds=JSON.parse(ct.canh_chon||'[]'); }catch(e){}
  const ten=id=>((taiSan.find(t=>t.id===id)||{}).ten)||id||'—';
  const cham=async(c,pq,tai_san_id)=>{ if(!c.mau_id) return; setBusy(true); const r=await goi('/ai/mau/'+c.mau_id,{method:'PATCH',body:{phan_quyet:pq, nhan:{tai_san_id}}}); setBusy(false); if(r.ok) notify('Đã chấm cảnh — máy học chọn cảnh'); else notify(r.msg,'err'); };
  if(!ds.length) return null;
  return <div className="mt-2 rounded-xl border border-line p-2 text-[11px]"><div className="font-semibold text-ink mb-1">Cảnh máy chọn (chấm để máy học — {ds[0].cach==='MO'?'mô hình mở đang chọn':'quy tắc từ khoá đang chọn'})</div>
    {ds.map(c=><div key={c.k} className="flex items-center gap-2 flex-wrap py-0.5 border-t border-line/60"><span className="font-semibold text-ink w-16 truncate">{c.label}</span><span className="text-ink-muted truncate max-w-[180px]" title={c.hinh}>💡 {c.hinh||'(không gợi ý)'}</span><span>→ <b>{ten(c.chon)}</b></span>{c.chon_mo&&c.chon_mo!==c.chon&&<span className="text-amber-700">· mở chọn: {ten(c.chon_mo)}</span>}
      {c.mau_id&&<div className="ml-auto flex gap-1 items-center"><Btn variant="ok" className="!py-0.5 !px-1.5 text-[11px]" onClick={()=>cham(c,'DUNG',c.chon)} disabled={busy}>✓ đúng</Btn><Select className="!py-0.5 !px-1 text-[11px] !w-40" value={chon[c.k]||''} onChange={e=>setChon({...chon,[c.k]:e.target.value})}><option value="">✗ cảnh đúng là…</option>{(c.ung_vien||[]).filter(u=>u.id!==c.chon).map(u=><option key={u.id} value={u.id}>{u.ten}</option>)}</Select>{chon[c.k]&&<Btn variant="ghost" className="!py-0.5 !px-1.5 text-[11px]" onClick={()=>cham(c,'SAI',chon[c.k])} disabled={busy}>lưu</Btn>}</div>}</div>)}
  </div>;
}
// ADR-009c — người giữ/bỏ đoạn máy cắt (loc_footage) và chấm giọng mở (tts)
function ChamLoc({ct, taiSan}){
  const { goi, notify } = useApp(); const [busy,setBusy]=useState(false); let ds=[]; try{ ds=JSON.parse(ct.loc_de_xuat||'[]'); }catch(e){}
  const cham=async(x,pq)=>{ if(!x.mau_id) return; setBusy(true); const r=await goi('/ai/mau/'+x.mau_id,{method:'PATCH',body:{phan_quyet:pq, nhan:pq==='DUNG'?{tai_san_id:x.tai_san_id}:{bo:true}}}); setBusy(false); if(r.ok) notify(pq==='DUNG'?'Giữ đoạn — máy học':'Bỏ đoạn — đã gỡ tài sản'); else notify(r.msg,'err'); };
  if(!ds.length) return null; const con=id=>taiSan.some(t=>t.id===id);
  return <div className="mt-2 rounded-xl border border-line p-2 text-[11px]"><div className="font-semibold text-ink mb-1">🤖 Đoạn máy cắt từ footage thô ({ct.loc_ghi_chu||''}) — giữ/bỏ để máy học lọc</div>
    {ds.map(x=><div key={x.k} className="flex items-center gap-2 flex-wrap py-0.5 border-t border-line/60"><span className="font-semibold text-ink w-16 truncate">{x.label}</span><span className="text-ink-muted truncate max-w-[200px]" title={x.hinh}>💡 {x.hinh}</span><span className="text-ink-muted">{x.tu}s–{x.den}s · điểm {x.diem}</span>{x.loi_noi&&<span className="text-ink-soft truncate max-w-[220px]" title={x.loi_noi}>🗣 {x.loi_noi}</span>}
      {con(x.tai_san_id)?<div className="ml-auto flex gap-1"><a className="text-brand-dark underline" href={(taiSan.find(t=>t.id===x.tai_san_id)||{}).media_url} target="_blank" rel="noreferrer">xem</a><Btn variant="ok" className="!py-0.5 !px-1.5 text-[11px]" onClick={()=>cham(x,'DUNG')} disabled={busy}>✓ giữ</Btn><Btn variant="ghost" className="!py-0.5 !px-1.5 text-[11px]" onClick={()=>cham(x,'SAI')} disabled={busy}>✗ bỏ</Btn></div>:<span className="ml-auto text-ink-muted">đã bỏ</span>}</div>)}
  </div>;
}
function ChamGiongMo({ct}){
  const { goi, notify } = useApp(); const [busy,setBusy]=useState(false); const [xong,setXong]=useState(false);
  const cham=async(pq)=>{ if(!ct.tts_mo_mau_id) return; setBusy(true); const r=await goi('/ai/mau/'+ct.tts_mo_mau_id,{method:'PATCH',body:{phan_quyet:pq}}); setBusy(false); if(r.ok){ notify('Đã chấm giọng mở'); setXong(true); } else notify(r.msg,'err'); };
  return <div className="mt-2 rounded-xl border border-line p-2 text-[11px] flex items-center gap-2 flex-wrap"><span className="font-semibold text-ink">🎙 Giọng đọc mở (Piper) đang chạy bóng — nghe thử:</span><audio controls src={ct.tts_mo_url} className="h-7"/>{!xong&&ct.tts_mo_mau_id&&<><Btn variant="ok" className="!py-0.5 !px-1.5 text-[11px]" onClick={()=>cham('DUNG')} disabled={busy}>✓ dùng được</Btn><Btn variant="ghost" className="!py-0.5 !px-1.5 text-[11px]" onClick={()=>cham('SAI')} disabled={busy}>✗ chưa được</Btn></>}<span className="text-ink-muted">Đủ mẫu ✓ → máy đề nghị gạt tts sang MỞ (hết phí Google)</span></div>;
}
// ----- Đăng (B9): lên lịch, cách đăng, đăng ngay, đánh dấu đã đăng tay -----
function DangTab({muc, nd, baiDang, taiSan, chiXem}){
  const { db, goi, notify } = useApp(); const [f,setF]=useState({kenh_id:muc.kenh_id||(nd&&nd.kenh_id)||'', gio_dang:'', cach:'', media_url:''}); const [busy,setBusy]=useState(false); const [linkTay,setLinkTay]=useState({});
  const kenh=(db.kenh||[]).find(k=>k.id===f.kenh_id); const kTen=id=>((db.kenh||[]).find(k=>k.id===id)||{}).ten||'—';
  const tao=async()=>{ setBusy(true); const r=await goi('/bai-dang',{method:'POST',body:{noi_dung_id:nd.id, kenh_id:f.kenh_id, gio_dang:f.gio_dang?new Date(f.gio_dang).toISOString():undefined, cach:f.cach||undefined, media_url:f.media_url||undefined}}); setBusy(false); if(r.ok) notify('Đã lên lịch đăng'); else notify(r.msg,'err'); };
  const dangNgay=async(b)=>{ setBusy(true); const r=await goi('/bai-dang/'+b.id+'/dang-ngay',{method:'POST'}); setBusy(false); if(r.ok&&!r.loi) notify(r.cho_callback?'Đã gửi n8n, chờ báo về':'Đã đăng: '+(r.link||'')); else notify(r.loi||r.msg,'err'); };
  const daDangTay=async(b)=>{ setBusy(true); const r=await goi('/bai-dang/'+b.id,{method:'PATCH',body:{da_dang:true, link:linkTay[b.id]||''}}); setBusy(false); if(r.ok) notify('Đã ghi nhận đăng tay → Đã đăng'); else notify(r.msg,'err'); };
  const b9=(db.buoc||[]).find(b=>b.ma==='B9')||{};
  return <div className="space-y-3">
    {!nd||nd.trang_thai!=='DUYET' ? <Callout tone="warn">Chỉ đưa vào đăng nội dung <b>đã duyệt (G3)</b>.</Callout> : !chiXem && <Card pad="p-3"><SectionTitle className="mb-2">Lên lịch đăng</SectionTitle>
      <div className="grid sm:grid-cols-4 gap-2 items-end">
        <Field label="Kênh" className="!mb-0"><Select className="!py-1.5 text-xs" value={f.kenh_id} onChange={e=>setF({...f,kenh_id:e.target.value})}><option value="">—</option>{(db.kenh||[]).filter(k=>k.active).map(k=><option key={k.id} value={k.id}>{k.ten}</option>)}</Select></Field>
        <Field label="Giờ đăng" hint={b9.nguoi_thuc_hien==='NGUOI'?'B9 đang do người → tới giờ máy giao việc đăng tay':'tới giờ máy tự đăng (API/n8n)'} className="!mb-0"><Input type="datetime-local" className="!py-1.5 text-xs" value={f.gio_dang} onChange={e=>setF({...f,gio_dang:e.target.value})}/></Field>
        <Field label="Cách đăng" className="!mb-0"><Select className="!py-1.5 text-xs" value={f.cach} onChange={e=>setF({...f,cach:e.target.value})}><option value="">theo kênh ({kenh?kenh.cach_dang:'—'})</option><option value="TAY">Đăng tay</option><option value="API">API nền tảng</option><option value="N8N">Qua n8n</option><option value="TRAM">Qua Trạm máy văn phòng</option></Select></Field>
        <Field label="Ảnh/video đính kèm" className="!mb-0"><Select className="!py-1.5 text-xs" value={f.media_url} onChange={e=>setF({...f,media_url:e.target.value})}><option value="">{nd.chi_tiet&&nd.chi_tiet.video_url?'video đã dựng':'—'}</option>{taiSan.map(t=><option key={t.id} value={t.media_url}>{t.ten}</option>)}</Select></Field></div>
      <div className="flex justify-end mt-2"><Btn variant="brand" onClick={tao} disabled={busy||!f.kenh_id}>🗓 Lên lịch</Btn></div></Card>}
    {baiDang.length===0?<Empty>Chưa có bài đăng nào.</Empty>:<Card pad="">{baiDang.map(b=><div key={b.id} className="px-3 py-2 border-b border-line/60 text-xs"><div className="flex items-center gap-2 flex-wrap"><Pill cls={(BD_TT[b.trang_thai]||[])[1]}>{(BD_TT[b.trang_thai]||[])[0]}</Pill><span className="font-semibold text-ink">{kTen(b.kenh_id)}</span><span className="text-ink-muted">{fmtDate(b.gio_dang)} · {b.cach}{b.link&&<> · <a className="text-brand-dark underline" href={b.link} target="_blank" rel="noreferrer">link</a></>}</span>{b.loi&&<span className="text-rose-600">· {b.loi}</span>}
        {!chiXem&&b.trang_thai!=='DA_DANG'&&<div className="ml-auto flex gap-1 items-center">{b.cach!=='TAY'&&b.cach!=='TRAM'&&<Btn variant="soft" className="!py-1 !px-2 text-[11px]" onClick={()=>dangNgay(b)} disabled={busy}>▶ Đăng ngay</Btn>}<Input className="!py-1 !px-2 !w-40 text-[11px]" placeholder="link đã đăng tay" value={linkTay[b.id]||''} onChange={e=>setLinkTay({...linkTay,[b.id]:e.target.value})}/><Btn variant="ok" className="!py-1 !px-2 text-[11px]" onClick={()=>daDangTay(b)} disabled={busy}>✓ Đã đăng tay</Btn></div>}</div>
      <div className="text-[11px] text-ink-muted mt-1 line-clamp-2 whitespace-pre-wrap">{b.noi_dung_dang}</div></div>)}</Card>}
  </div>;
}
