// ===== MÀN SEEDING HỘI NHÓM FACEBOOK (ADR-007 · bản vẽ §11) — MKT tự vận hành: gói (G3-gói) · lịch & việc · nhóm · tài khoản MKT · lead · hiệu quả =====
const VS_TT = { CHO:['Chờ giờ','bg-slate-100 text-ink'], DANG_GUI:['Đang gửi Trạm','bg-sky-100 text-sky-800'], DA_DANG:['Đã đăng','bg-emerald-100 text-emerald-800'], CHO_QUAN_TRI:['Chờ QTV nhóm duyệt','bg-violet-100 text-violet-800'], LOI:['Lỗi','bg-rose-100 text-rose-700'], DAT:['✓ Đạt','bg-emerald-100 text-emerald-800'], KHONG_DAT:['✗ Không đạt','bg-rose-100 text-rose-700'], NGHI_NGO:['⚠ Nghi ngờ','bg-amber-100 text-amber-800'], HUY:['Huỷ','bg-slate-100 text-ink-muted'] };
const GOI_TT = { NHAP:['Nháp','bg-slate-100 text-ink-muted'], CHO_DUYET:['Chờ duyệt (G3-gói)','bg-amber-100 text-amber-800'], DUYET:['Đã duyệt','bg-emerald-100 text-emerald-800'], TRA_LAI:['Trả lại','bg-rose-100 text-rose-700'], HET_HAN:['Hết hạn','bg-slate-100 text-ink-muted'] };
const GIONG_LABEL = { THO:'Thợ', THAU:'Thầu', CHU_NHA:'Chủ nhà' };
const DANG_LABEL = { KE:'Kể trải nghiệm', HOI:'Hỏi tư vấn', KHOE:'Khoe công trình', SO_SANH:'So sánh', CANH_BAO:'Cảnh báo lỗi' };
const VAI_BL = { HOI_KN:'hỏi kinh nghiệm', XAC_NHAN:'xác nhận đã dùng', HOI_MUA:'hỏi mua' };
function SeedingHoiNhom(){
  const { db, me } = useApp(); const S=db.seeding||{}; const chiXem=!laStaff(me); const [tab,setTab]=useState('goi');
  const nghiNgo=(S.viec||[]).filter(v=>v.trang_thai==='NGHI_NGO').length; const choDuyet=(S.goi||[]).filter(g=>g.trang_thai==='CHO_DUYET').length; const leadMoi=(S.lead||[]).filter(l=>l.trang_thai==='MOI').length;
  return <div className="space-y-4">
    <PageHeader title="📣 Seeding hội nhóm Facebook" sub="Định vị → bản đồ thông điệp → máy soạn gói biến thể (giọng thợ/thầu/chủ nhà) → Trưởng MKT duyệt cả gói (G3-gói) → máy xếp nhóm × tài khoản MKT × giờ vàng → Trạm đăng → Trạm kiểm, đo, bắt lead → học."/>
    <Tabs size="sm" active={tab} onChange={setTab} tabs={[{key:'goi',label:'Gói & duyệt',count:choDuyet||null},{key:'viec',label:'Lịch & việc',count:(S.viec||[]).filter(v=>['CHO','DANG_GUI'].includes(v.trang_thai)).length||null},{key:'nhom',label:'Nhóm',count:(S.nhom||[]).filter(n=>n.active).length||null},{key:'taikhoan',label:'Tài khoản MKT',count:(S.tai_khoan||[]).filter(t=>t.active).length||null},{key:'lead',label:'Lead',count:leadMoi||null},{key:'binhluan',label:'Bình luận & nuôi',count:(S.binh_luan||[]).filter(b=>['CHO','DANG_GUI'].includes(b.trang_thai)).length||null},{key:'nghingo',label:'Nghi ngờ',count:nghiNgo||null},{key:'hieuqua',label:'Hiệu quả'}]}/>
    {tab==='goi' && <SeedingGoi S={S} chiXem={chiXem}/>}{tab==='viec' && <SeedingViec S={S} chiXem={chiXem}/>}{tab==='nhom' && <SeedingNhom S={S} chiXem={chiXem}/>}{tab==='taikhoan' && <SeedingTaiKhoan S={S}/>}{tab==='lead' && <SeedingLead S={S} chiXem={chiXem}/>}{tab==='binhluan' && <SeedingBinhLuan S={S} chiXem={chiXem}/>}{tab==='nghingo' && <SeedingNghiNgo S={S} chiXem={chiXem}/>}{tab==='hieuqua' && <SeedingHieuQua S={S}/>}
  </div>;
}
function SeedingGoi({S, chiXem}){
  const { db, me, goi, notify } = useApp(); const duyetDuoc=laGat(me); const [busy,setBusy]=useState(false); const [sua,setSua]=useState(null); const [chon,setChon]=useState(''); const [loc,setLoc]=useState('MO'); const [lyDo,setLyDo]=useState({});
  const baiDang=(db.bai_dang||[]).filter(b=>b.trang_thai==='DA_DANG'&&!(S.goi||[]).some(g=>g.bai_dang_id===b.id)); const mucCua=id=>(db.muc_noi_dung||[]).find(m=>m.id===id)||{}; const tdCua=id=>(S.thong_diep||[]).find(t=>t.id===id)||{};
  const goiDs=(S.goi||[]).filter(g=>loc==='MO'?['NHAP','CHO_DUYET','DUYET'].includes(g.trang_thai):true);
  const tao=async(dinhKy)=>{ setBusy(true); const r=await goi('/seeding/goi',{method:'POST',body:dinhKy?{}:{bai_dang_id:chon}}); setBusy(false); if(r.ok){ notify('Gói '+r.so_bien_the+' biến thể · máy chấm '+(r.cham||{}).diem+'/100'+(r.tu_duyet?' · tự duyệt (B13 AI tự làm)':' · chờ Trưởng MKT duyệt')); setChon(''); } else notify(r.msg,'err'); };
  const hanh=async(g,hd,body)=>{ setBusy(true); const r=await goi('/seeding/goi/'+g.id+'/'+hd,{method:'POST',body:body||{}}); setBusy(false); if(r.ok) notify(hd==='duyet'?('Đã duyệt gói'+(r.xep!=null?(' · máy xếp '+r.xep+' việc'):'')):hd==='xep-lich'?('Xếp '+r.xep+' việc'+((r.bo||[]).length?(' · '+r.bo.slice(0,2).join('; ')):'')):'Đã cập nhật'); else notify(r.msg,'err'); };
  const luuBT=async()=>{ setBusy(true); const r=await goi('/seeding/bien-the/'+sua.id,{method:'PATCH',body:{noi_dung:sua.noi_dung, binh_luan:sua.binh_luan.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{ const m=x.match(/^(HOI_KN|XAC_NHAN|HOI_MUA)\s*[:：]\s*(.+)$/i); return m?{vai:m[1].toUpperCase(),text:m[2]}:{vai:'HOI_KN',text:x}; })}}); setBusy(false); if(r.ok){ notify('Đã lưu (máy học B13)'); setSua(null); } else notify(r.msg,'err'); };
  const b13=(db.buoc||[]).find(b=>b.ma==='B13')||{};
  return <div className="space-y-3">
    {!chiXem&&<Card pad="p-3"><div className="flex items-center gap-2 flex-wrap"><SectionTitle>Tạo gói</SectionTitle>
      <Btn variant="brand" className="!py-1.5 text-xs" onClick={()=>tao(true)} disabled={busy||!db.san_sang.ai||!(S.thong_diep||[]).some(t=>t.active)} title={!db.san_sang.ai?'Cần ANTHROPIC_API_KEY':!(S.thong_diep||[]).some(t=>t.active)?'Chưa có thông điệp (Chiến lược › Thông điệp seeding)':''}>✨ Gói định kỳ theo bản đồ thông điệp</Btn>
      <span className="text-ink-muted text-xs">hoặc</span><Select className="!w-72 !py-1.5 text-xs" value={chon} onChange={e=>setChon(e.target.value)}><option value="">— bài chính đã đăng chưa có gói —</option>{baiDang.map(b=><option key={b.id} value={b.id}>{(mucCua(b.muc_id).tieu_de||b.noi_dung_dang||'').slice(0,60)} · {fmtDate(b.posted_at)}</option>)}</Select><Btn variant="soft" className="!py-1.5 text-xs" onClick={()=>tao(false)} disabled={busy||!chon||!db.san_sang.ai}>✨ Gói cho bài chính</Btn></div>
      <div className="text-[11px] text-ink-muted mt-1">B13 đang ở <b>{MUC_LABEL[b13.nguoi_thuc_hien]}</b>: máy tự soạn gói định kỳ theo chỉ tiêu tuần (Kế hoạch tháng) và gói cho bài chính mới đăng; {b13.nguoi_thuc_hien==='AI_TU_LAM'?'gói máy chấm ĐẠT được tự duyệt.':'mọi gói chờ Trưởng MKT duyệt (G3-gói) — mỗi lần duyệt/trả là mẫu học.'}</div></Card>}
    <Tabs size="sm" active={loc} onChange={setLoc} tabs={[{key:'MO',label:'Đang mở'},{key:'ALL',label:'Tất cả (60 ngày)'}]}/>
    {goiDs.length===0?<Empty>Chưa có gói seeding nào.</Empty>:goiDs.map(g=>{ const bts=(S.bien_the||[]).filter(b=>b.goi_id===g.id); const vs=(S.viec||[]).filter(v=>v.goi_id===g.id); const bd=(db.bai_dang||[]).find(b=>b.id===g.bai_dang_id)||{}; const cm=g.cham_may||{}; return <Card key={g.id}>
      <div className="flex items-center justify-between gap-2 flex-wrap"><div><SectionTitle>{g.loai==='DINH_KY'?'🔁 Gói định kỳ':'📎 '+(mucCua(g.muc_id).tieu_de||(bd.noi_dung_dang||'').slice(0,60))}</SectionTitle><div className="text-[11px] text-ink-muted flex items-center gap-1 flex-wrap"><Pill cls={(GOI_TT[g.trang_thai]||[])[1]}>{(GOI_TT[g.trang_thai]||[])[0]}</Pill>{bts.length} biến thể · {vs.length} việc ({vs.filter(v=>v.trang_thai==='DAT').length} đạt) · hạn {g.han} · {g.tao_boi}{cm.diem!=null&&<span title={(cm.ly||[]).join('; ')}> · máy chấm <b>{cm.diem}</b>/100{(cm.ly||[]).length?(' — '+cm.ly.slice(0,2).join('; ')):''}</span>}{g.duyet_boi&&<> · {g.trang_thai==='TRA_LAI'?'trả lại':'duyệt'} bởi {g.duyet_boi}{g.ly_do?(': '+g.ly_do):''}</>}{bd.link&&<> · <a className="text-brand-dark underline" href={bd.link} target="_blank" rel="noreferrer">bài chính</a></>}</div></div>
        {!chiXem&&<div className="flex gap-1 items-center flex-wrap">{g.trang_thai==='CHO_DUYET'&&duyetDuoc&&<><Input className="!py-1 !px-2 text-[11px] !w-48" placeholder="lý do (bắt buộc khi trả)" value={lyDo[g.id]||''} onChange={e=>setLyDo({...lyDo,[g.id]:e.target.value})}/><Btn variant="ok" className="!py-1 !px-2 text-[11px]" onClick={()=>hanh(g,'duyet',{ly_do:lyDo[g.id]||''})} disabled={busy}>✓ Duyệt cả gói</Btn><Btn variant="ghost" className="!py-1 !px-2 text-[11px]" onClick={()=>{ if(!(lyDo[g.id]||'').trim()) return notify('Trả lại phải ghi lý do','err'); hanh(g,'tra-lai',{ly_do:lyDo[g.id]}); }} disabled={busy}>↩ Trả lại</Btn></>}{g.trang_thai==='CHO_DUYET'&&!duyetDuoc&&<span className="text-[11px] text-ink-muted">chờ Trưởng MKT</span>}{['NHAP','TRA_LAI'].includes(g.trang_thai)&&<Btn variant="soft" className="!py-1 !px-2 text-[11px]" onClick={()=>hanh(g,'gui-duyet')} disabled={busy}>Gửi duyệt lại</Btn>}{g.trang_thai==='DUYET'&&<Btn variant="ghost" className="!py-1 !px-2 text-[11px]" onClick={()=>hanh(g,'xep-lich')} disabled={busy}>🗓 Xếp thêm lịch</Btn>}</div>}</div>
      <div className="grid md:grid-cols-3 gap-2 mt-2">{bts.map(b=><div key={b.id} className="rounded-xl border border-line p-2 text-[11px]"><div className="flex items-center justify-between gap-1 flex-wrap"><div className="flex gap-1"><Pill cls="bg-brand-bg text-brand-dark">{GIONG_LABEL[b.giong]||b.giong}</Pill><Pill>{DANG_LABEL[b.dang_bai]||b.dang_bai}</Pill>{b.co_link&&<Pill cls="bg-amber-100 text-amber-800">link</Pill>}</div><span className="text-ink-muted">{b.tao_boi==='AGENT'?'🤖':'👤'}{b.sua_boi?(' · sửa: '+b.sua_boi):''}</span></div>
        <div className="text-[11px] text-ink-muted mt-0.5">💡 {tdCua(b.thong_diep_id).ten||'—'}</div>
        {sua&&sua.id===b.id?<div className="mt-1 space-y-1"><Textarea rows="6" className="text-[11px]" value={sua.noi_dung} onChange={e=>setSua({...sua,noi_dung:e.target.value})}/><Textarea rows="3" className="text-[11px]" value={sua.binh_luan} onChange={e=>setSua({...sua,binh_luan:e.target.value})} placeholder={'mỗi dòng một bình luận dẫn dắt, ví dụ:\nHOI_KN: Bác dùng loại nào vậy?\nHOI_MUA: Mua ở đâu anh?'}/><div className="flex gap-1 justify-end"><Btn variant="ghost" className="!py-1 !px-2 text-[11px]" onClick={()=>setSua(null)}>Huỷ</Btn><Btn variant="brand" className="!py-1 !px-2 text-[11px]" onClick={luuBT} disabled={busy}>Lưu</Btn></div></div>
        :<><div className="text-ink mt-1 whitespace-pre-wrap">{b.noi_dung}</div>{(b.binh_luan||[]).length>0&&<div className="text-ink-muted mt-1">💬 {b.binh_luan.map((c,i)=><span key={i}><i>{VAI_BL[c.vai]||c.vai}</i>: {c.text}{i<b.binh_luan.length-1?' · ':''}</span>)}</div>}{!chiXem&&['NHAP','CHO_DUYET','TRA_LAI','DUYET'].includes(g.trang_thai)&&<LinkBtn className="mt-1" onClick={()=>setSua({id:b.id, noi_dung:b.noi_dung, binh_luan:(b.binh_luan||[]).map(c=>c.vai+': '+c.text).join('\n')})}>✏️ Sửa</LinkBtn>}</>}</div>)}</div>
    </Card>; })}
  </div>;
}
function SeedingViec({S, chiXem}){
  const { db, me, goi, notify } = useApp(); const [busy,setBusy]=useState(false); const [loc,setLoc]=useState('MO');
  const nhomCua=id=>(S.nhom||[]).find(n=>n.id===id)||{}; const btCua=id=>(S.bien_the||[]).find(b=>b.id===id)||{}; const tkCua=id=>(S.tai_khoan||[]).find(t=>t.id===id)||{};
  const ds=(S.viec||[]).filter(v=>loc==='MO'?['CHO','DANG_GUI','LOI','CHO_QUAN_TRI'].includes(v.trang_thai):loc==='DA'?['DA_DANG','DAT','KHONG_DAT','NGHI_NGO'].includes(v.trang_thai):true);
  const hanh=async(v,hd,body)=>{ setBusy(true); const r=await goi('/seeding/viec/'+v.id+'/'+hd,{method:'POST',body:body||{}}); setBusy(false); if(r.ok) notify(r.tom_tat||'Đã cập nhật'); else notify(r.msg,'err'); };
  const chayThu=async(ma)=>{ setBusy(true); const r=await goi('/may/chay-thu',{method:'POST',body:{agent:ma}}); setBusy(false); if(r.ok) notify((r.kq[0]||{}).tom_tat||(r.kq[0]||{}).bo_qua||'Xong'); else notify(r.msg,'err'); };
  const b15=(db.buoc||[]).find(b=>b.ma==='B15')||{}; const tt=(db.tram||{}).trang_thai; const cfg=(db.module_config||{}).seeding||{};
  return <div className="space-y-3">
    <Callout tone="info">B15 đang ở <b>{MUC_LABEL[b15.nguoi_thuc_hien]}</b>{b15.nguoi_thuc_hien==='NGUOI'?' → tới giờ máy giao việc đăng tay (copy biến thể, đăng, dán link)':' → tới giờ Trạm đăng bằng tài khoản MKT'} · Trạm {tt&&tt.song?'🟢 sống':'🔴 im (việc sẽ được dời 30 phút)'} · giờ vàng mặc định {(cfg.gio_vang||[]).join('h, ')}h · mỗi tài khoản cách nhau ≥ {cfg.khoang_cach_phut} phút.{laGat(me)&&<> <LinkBtn onClick={()=>chayThu('TAO_GOI_SEEDING')}>▶ Soạn gói</LinkBtn> · <LinkBtn onClick={()=>chayThu('XEP_LICH_SEEDING')}>▶ Xếp lịch</LinkBtn> · <LinkBtn onClick={()=>chayThu('DANG_SEEDING')}>▶ Đẩy việc tới giờ</LinkBtn> · <LinkBtn onClick={()=>chayThu('KIEM_SEEDING')}>▶ Kiểm bài</LinkBtn></>}</Callout>
    <Tabs size="sm" active={loc} onChange={setLoc} tabs={[{key:'MO',label:'Chờ đăng'},{key:'DA',label:'Đã đăng / đã kiểm'},{key:'ALL',label:'Tất cả'}]}/>
    {ds.length===0?<Empty>Không có việc. Máy xếp lịch (B14) cho gói đã duyệt khi có nhóm bật + tài khoản trong nhóm còn sống.</Empty>:<Card pad="">{ds.map(v=>{ const n=nhomCua(v.nhom_id), b=btCua(v.bien_the_id), t=tkCua(v.tai_khoan_id); return <div key={v.id} className="px-3 py-2 border-b border-line/60 text-xs">
      <div className="flex items-center gap-2 flex-wrap"><Pill cls={(VS_TT[v.trang_thai]||[])[1]}>{(VS_TT[v.trang_thai]||[])[0]}</Pill><span className="font-semibold text-ink">📘 {n.ten||'—'}</span><span className="text-ink-muted">{fmtDate(v.gio_dang)} · {t.nhan||'(chưa gán tài khoản)'} · {GIONG_LABEL[b.giong]||b.giong} · {DANG_LABEL[b.dang_bai]||''} · {v.cach}</span>{v.link&&<a className="text-brand-dark underline" href={v.link} target="_blank" rel="noreferrer">link</a>}{v.loi&&<span className="text-rose-600">· {v.loi}</span>}{v.ly_do&&<span className="text-ink-muted">· {v.ly_do}</span>}{v.kiem&&v.kiem.react!=null&&<span className="text-ink-muted">· {v.kiem.react} react · {v.kiem.binh_luan||0} bl{v.kiem.lead?(' · '+v.kiem.lead+' lead'):''}{v.kiem.khop!=null?(' · khớp '+v.kiem.khop+'%'):''}</span>}
        {!chiXem&&<div className="ml-auto flex gap-1">{v.trang_thai==='CHO'&&<Btn variant="soft" className="!py-1 !px-2 text-[11px]" onClick={()=>hanh(v,'dang-ngay')} disabled={busy}>▶ Đăng ngay</Btn>}{['CHO','DANG_GUI','LOI','CHO_QUAN_TRI'].includes(v.trang_thai)&&<Btn variant="ghost" className="!py-1 !px-2 text-[11px]" onClick={()=>{ const l=prompt('Đã đăng / QTV đã duyệt — dán link bài:'); if(l!==null) hanh(v,'da-dang',{link:l}); }} disabled={busy}>✓ Đã lên</Btn>}{!['HUY','DAT','KHONG_DAT'].includes(v.trang_thai)&&<Btn variant="ghost" className="!py-1 !px-2 text-[11px]" onClick={()=>{ const l=prompt('Lý do huỷ:'); if(l!==null) hanh(v,'huy',{ly_do:l}); }} disabled={busy}>Huỷ</Btn>}</div>}</div>
      <div className="text-[11px] text-ink-soft mt-1 line-clamp-2 whitespace-pre-wrap">{b.noi_dung}</div></div>; })}</Card>}
  </div>;
}
function SeedingNhom({S, chiXem}){
  const { goi, notify } = useApp(); const [edit,setEdit]=useState(null); const [busy,setBusy]=useState(false);
  const luu=async()=>{ setBusy(true); const r=await goi('/seeding/nhom'+(edit.id?('/'+edit.id):''),{method:edit.id?'PATCH':'POST',body:{...edit, gio_vang:String(edit.gio_vang_text||'').split(/[,\s]+/).filter(Boolean)}}); setBusy(false); if(r.ok){ notify('Đã lưu'); setEdit(null); } else notify(r.msg,'err'); };
  const tkTen=ids=>(ids||[]).map(id=>((S.tai_khoan||[]).find(t=>t.id===id)||{}).nhan).filter(Boolean).join(', ')||'— chưa gán —';
  const qtText=q=>[q.duyet_bai&&'QTV duyệt bài', q.cam_ban_hang&&'cấm bán hàng', q.cam_link&&'cấm link'].filter(Boolean).join(' · ')||'tự do';
  return <div className="space-y-3">
    <div className="flex items-center justify-between"><SectionTitle>Nhóm Facebook đích ({(S.nhom||[]).filter(n=>n.active).length} đang bật)</SectionTitle>{!chiXem&&<Btn variant="brand" className="!py-1.5 text-xs" onClick={()=>setEdit({cach:'TRAM', nhip_tuan:1, active:true, quy_tac:{}, tai_khoan_ids:[], gio_vang_text:''})}>＋ Thêm nhóm</Btn>}</div>
    <Callout tone="note">Khai <b>quy tắc nhóm</b> để máy chọn biến thể hợp lệ (nhóm cấm link → không đăng bài có link; QTV duyệt bài → việc chờ QTV, Trạm kiểm lại sau). <b>Giờ vàng</b> riêng của nhóm (nếu để trống dùng mặc định). Chỉ gán <b>tài khoản MKT đã là thành viên</b> nhóm. Nhịp/tuần thấp để không spam; nhóm bị gỡ bài nhiều máy sẽ đề xuất tắt (G4).</Callout>
    <Card pad="">{(S.nhom||[]).length===0?<Empty>Chưa khai nhóm nào — máy không xếp lịch được.</Empty>:<table className="w-full text-xs"><thead><tr className="text-left text-ink-muted border-b border-line"><th className="px-3 py-2">Nhóm</th><th className="px-3 py-2">Quy tắc</th><th className="px-3 py-2">Giờ vàng</th><th className="px-3 py-2">Tài khoản trong nhóm</th><th className="px-3 py-2">Nhịp/tuần</th><th className="px-3 py-2">Hiệu quả</th><th/></tr></thead><tbody>{(S.nhom||[]).map(n=><tr key={n.id} className={"border-b border-line/60 "+(n.active?'':'opacity-50')}><td className="px-3 py-2"><div className="font-semibold text-ink">{n.ten} {n.cach==='TAY'&&<Pill>đăng tay</Pill>}</div><div className="text-[11px] text-ink-muted truncate max-w-[220px]">{n.link_hoac_id} {n.chu_de&&('· '+n.chu_de)}</div></td><td className="px-3 py-2 text-[11px]">{qtText(n.quy_tac||{})}</td><td className="px-3 py-2">{(n.gio_vang||[]).length?n.gio_vang.join('h, ')+'h':'mặc định'}</td><td className="px-3 py-2">{tkTen(n.tai_khoan_ids)}</td><td className="px-3 py-2">{n.nhip_tuan}</td><td className="px-3 py-2 text-[11px] text-ink-muted">{n.hieu_qua.tong?(Math.round(100*(n.hieu_qua.dat||0)/n.hieu_qua.tong)+'% đạt · '+Math.round((n.hieu_qua.react||0)/n.hieu_qua.tong)+' react/bài'+(n.hieu_qua.lead?(' · '+n.hieu_qua.lead+' lead'):'')+(n.hieu_qua.go?(' · '+n.hieu_qua.go+' bị gỡ'):'')):'—'}</td><td className="px-3 py-2 text-right">{!chiXem&&<LinkBtn onClick={()=>setEdit({...n, gio_vang_text:(n.gio_vang||[]).join(', ')})}>Sửa</LinkBtn>}</td></tr>)}</tbody></table>}</Card>
    {edit&&<Modal open onClose={()=>setEdit(null)} title={edit.id?'Sửa nhóm':'Thêm nhóm seeding'}>
      <Field label="Tên nhóm" required><Input value={edit.ten||''} onChange={e=>setEdit({...edit,ten:e.target.value})}/></Field>
      <Field label="Link nhóm Facebook"><Input value={edit.link_hoac_id||''} onChange={e=>setEdit({...edit,link_hoac_id:e.target.value})} placeholder="https://www.facebook.com/groups/…"/></Field>
      <div className="grid grid-cols-2 gap-2"><Field label="Chủ đề"><Input value={edit.chu_de||''} onChange={e=>setEdit({...edit,chu_de:e.target.value})} placeholder="thợ ốp lát, hoàn thiện nhà…"/></Field><Field label="Cách đăng"><Select value={edit.cach} onChange={e=>setEdit({...edit,cach:e.target.value})}><option value="TRAM">Trạm tự đăng</option><option value="TAY">Người đăng tay</option></Select></Field></div>
      <Field label="Quy tắc nhóm"><div className="flex gap-4 flex-wrap text-sm">{[['duyet_bai','QTV duyệt bài'],['cam_ban_hang','Cấm bán hàng'],['cam_link','Cấm link']].map(([k,l])=><label key={k} className="flex items-center gap-1"><input type="checkbox" checked={!!(edit.quy_tac||{})[k]} onChange={e=>setEdit({...edit,quy_tac:{...(edit.quy_tac||{}),[k]:e.target.checked}})}/> {l}</label>)}</div></Field>
      <div className="grid grid-cols-2 gap-2"><Field label="Giờ vàng (giờ VN, cách nhau dấu phẩy)" hint="trống = mặc định cấu hình"><Input value={edit.gio_vang_text||''} onChange={e=>setEdit({...edit,gio_vang_text:e.target.value})} placeholder="6, 12, 20"/></Field><Field label="Nhịp tối đa / tuần"><Input type="number" min="1" max="7" value={edit.nhip_tuan} onChange={e=>setEdit({...edit,nhip_tuan:e.target.value})}/></Field></div>
      <Field label="Tài khoản MKT đã ở trong nhóm"><div className="flex gap-3 flex-wrap text-sm">{(S.tai_khoan||[]).filter(t=>t.active).map(t=><label key={t.id} className="flex items-center gap-1"><input type="checkbox" checked={(edit.tai_khoan_ids||[]).includes(t.id)} onChange={e=>setEdit({...edit,tai_khoan_ids:e.target.checked?[...(edit.tai_khoan_ids||[]),t.id]:(edit.tai_khoan_ids||[]).filter(x=>x!==t.id)})}/> {t.nhan} <span className="text-ink-muted">({GIONG_LABEL[t.giong]})</span></label>)}{(S.tai_khoan||[]).filter(t=>t.active).length===0&&<span className="text-ink-muted text-xs">chưa có tài khoản — khai ở tab Tài khoản MKT</span>}</div></Field>
      <Field label="Ghi chú"><Input value={edit.ghi_chu||''} onChange={e=>setEdit({...edit,ghi_chu:e.target.value})}/></Field>
      {edit.id&&<label className="flex items-center gap-2 text-sm mb-3"><Toggle on={edit.active!==false} onChange={v=>setEdit({...edit,active:v})}/> Đang bật</label>}
      <div className="flex justify-end gap-2"><Btn variant="ghost" onClick={()=>setEdit(null)}>Huỷ</Btn><Btn variant="brand" onClick={luu} disabled={busy||!(edit.ten||'').trim()}>Lưu</Btn></div></Modal>}
  </div>;
}
function SeedingTaiKhoan({S}){
  const { me, goi, notify } = useApp(); const duoc=laGat(me); const [edit,setEdit]=useState(null); const [busy,setBusy]=useState(false);
  const luu=async()=>{ setBusy(true); const r=await goi('/seeding/tai-khoan'+(edit.id?('/'+edit.id):''),{method:edit.id?'PATCH':'POST',body:{...edit, ...(edit.persona||{})}}); setBusy(false); if(r.ok){ notify('Đã lưu'); setEdit(null); } else notify(r.msg,'err'); };
  const soNhom=id=>(S.nhom||[]).filter(n=>n.active&&(n.tai_khoan_ids||[]).includes(id)).length; const phienTram=(((useApp().db.tram||{}).trang_thai)||{}).phien||{}; const tramSong=!!(((useApp().db.tram||{}).trang_thai)||{}).song; const dnTram=t=>{ const p=phienTram[t.tram_id]; return !tramSong?null:(p?!!p.co_phien:false); };
  return <div className="space-y-3">
    <div className="flex items-center justify-between"><SectionTitle>Tài khoản Facebook của phòng MKT trên Trạm ({(S.tai_khoan||[]).filter(t=>t.active).length})</SectionTitle>{duoc&&<Btn variant="brand" className="!py-1.5 text-xs" onClick={()=>setEdit({tram_id:'facebook', giong:'THO', nhip_ngay:2, active:true, persona:{}})}>＋ Thêm</Btn>}</div>
    <Callout tone="note">Đăng nhập tài khoản trên máy Trạm: mở trang Trạm (máy Ngoc-Han, cổng 8899) › thẻ <b>facebook</b>, <b>facebook-2</b>… <b>facebook-5</b> › bấm Đăng nhập, đăng nhập tay trong cửa sổ hiện ra một lần; Trạm giữ phiên, không giữ mật khẩu. Mỗi tài khoản giữ <b>một giọng cố định</b> (thợ / thầu / chủ nhà) và một câu chuyện nền để bài viết nhất quán; nên 2–5 tài khoản. Content OS không giữ mật khẩu — chỉ ghi <b>hồ sơ trên Trạm</b> (<code>facebook</code> cho tài khoản chính, <code>facebook-2</code>, <code>facebook-3</code>… cho tài khoản thêm; đăng nhập một lần trên máy Trạm). Gặp checkpoint/captcha máy tự tạm dừng tài khoản 24 giờ và giao việc kiểm tra — không bao giờ tự vượt.</Callout>
    <Card pad="">{(S.tai_khoan||[]).length===0?<Empty>Chưa khai tài khoản nào.</Empty>:<div className="divide-y divide-line">{(S.tai_khoan||[]).map(t=><div key={t.id} className={"px-3 py-2 flex items-center gap-3 text-xs "+(t.active?'':'opacity-50')}><span>📘</span><div className="min-w-0 flex-1"><div className="font-semibold text-ink">{t.nhan} <Pill cls="bg-brand-bg text-brand-dark">{GIONG_LABEL[t.giong]||t.giong}</Pill> {(t.persona||{}).tu_tram&&!(t.persona||{}).cau_chuyen&&<Pill cls="bg-amber-50 text-amber-800">tự khai từ Trạm · chọn giọng & câu chuyện</Pill>} <span className="text-ink-muted font-normal">· hồ sơ {t.tram_id} · ≤ {t.nhip_ngay} bài/ngày · trong {soNhom(t.id)} nhóm</span></div><div className="text-[11px] text-ink-muted">{dnTram(t)===true?<span className="text-emerald-700">● đã đăng nhập trên Trạm · </span>:dnTram(t)===false?<span className="text-rose-700">○ chưa đăng nhập trên Trạm (mở trang Trạm › Tài khoản › dòng “{t.tram_id}” › Đăng nhập) · </span>:<span>Trạm im · </span>}{(()=>{ const p=phienTram[t.tram_id]||{}; return <>{p.dung_den&&p.dung_den>new Date().toISOString()&&<span className="text-rose-700">⏸ Trạm dừng tới {fmtDate(p.dung_den)} (checkpoint{p.checkpoint_30d?(' · '+p.checkpoint_30d+' lần/30 ngày'):''}) · </span>}{p.dang_dung_boi&&<span className="text-amber-700">đang được {p.dang_dung_boi} dùng · </span>}</>; })()}{t.song?'● sẵn sàng':(t.tam_dung_den?('⏸ tạm dừng tới '+fmtDate(t.tam_dung_den)+(t.suc_khoe.loi?(' — '+t.suc_khoe.loi):'')):'○ tắt')}{t.suc_khoe.tong?(' · '+t.suc_khoe.tong+' bài, '+Math.round(100*(t.suc_khoe.dat||0)/t.suc_khoe.tong)+'% đạt'):''}{(t.persona||{}).cau_chuyen?(' · '+t.persona.cau_chuyen.slice(0,80)):''}</div></div>{duoc&&<div className="flex gap-2">{t.tam_dung_den&&<LinkBtn onClick={async()=>{ const r=await goi('/seeding/tai-khoan/'+t.id,{method:'PATCH',body:{mo_lai:true}}); if(r.ok) notify('Đã mở lại'); }}>Mở lại</LinkBtn>}<LinkBtn onClick={()=>setEdit({...t})}>Sửa</LinkBtn></div>}</div>)}</div>}</Card>
    {edit&&<Modal open onClose={()=>setEdit(null)} title={edit.id?'Sửa tài khoản':'Thêm tài khoản MKT'}>
      <Field label="Nhãn" required><Input value={edit.nhan||''} onChange={e=>setEdit({...edit,nhan:e.target.value})} placeholder="VD: Anh Tư thợ ốp"/></Field>
      <div className="grid grid-cols-2 gap-2"><Field label="Giọng cố định"><Select value={edit.giong} onChange={e=>setEdit({...edit,giong:e.target.value})}>{(S.giong||[]).map(g=><option key={g[0]} value={g[0]}>{GIONG_LABEL[g[0]]} — {g[1]}</option>)}</Select></Field><Field label="Hồ sơ trên Trạm" hint="facebook · facebook-2 · facebook-3…"><Input value={edit.tram_id||''} onChange={e=>setEdit({...edit,tram_id:e.target.value})}/></Field></div>
      <div className="grid grid-cols-2 gap-2"><Field label="Nghề (persona)"><Input value={(edit.persona||{}).nghe||''} onChange={e=>setEdit({...edit,persona:{...(edit.persona||{}),nghe:e.target.value}})} placeholder="thợ ốp lát 12 năm"/></Field><Field label="Khu vực"><Input value={(edit.persona||{}).khu_vuc||''} onChange={e=>setEdit({...edit,persona:{...(edit.persona||{}),khu_vuc:e.target.value}})} placeholder="Bình Dương"/></Field></div>
      <Field label="Câu chuyện nền" hint="máy giữ nhất quán qua các bài"><Textarea rows="2" value={(edit.persona||{}).cau_chuyen||''} onChange={e=>setEdit({...edit,persona:{...(edit.persona||{}),cau_chuyen:e.target.value}})}/></Field>
      <Field label="Nhịp tối đa / ngày" hint="giữ thấp để không bị khoá"><Input type="number" min="1" max="10" value={edit.nhip_ngay} onChange={e=>setEdit({...edit,nhip_ngay:e.target.value})}/></Field>
      {edit.id&&<label className="flex items-center gap-2 text-sm mb-3"><Toggle on={edit.active!==false} onChange={v=>setEdit({...edit,active:v})}/> Đang dùng</label>}
      <div className="flex justify-end gap-2"><Btn variant="ghost" onClick={()=>setEdit(null)}>Huỷ</Btn><Btn variant="brand" onClick={luu} disabled={busy||!(edit.nhan||'').trim()}>Lưu</Btn></div></Modal>}
  </div>;
}
function SeedingLead({S, chiXem}){
  const { goi, notify } = useApp(); const [loc,setLoc]=useState('MOI'); const [busy,setBusy]=useState(false);
  const ds=(S.lead||[]).filter(l=>loc==='MOI'?l.trang_thai==='MOI':true); const viecCua=id=>(S.viec||[]).find(v=>v.id===id)||{}; const nhomCua=id=>(S.nhom||[]).find(n=>n.id===id)||{};
  const cap=async(l,tt)=>{ const g=prompt(tt==='DA_TRA_LOI'?'Đã trả lời thế nào? (ghi ngắn để học)':'Ghi chú khi chuyển Sales:'); if(g===null) return; setBusy(true); const r=await goi('/seeding/lead/'+l.id,{method:'PATCH',body:{trang_thai:tt, ghi_chu:g}}); setBusy(false); if(r.ok) notify('Đã cập nhật lead'); else notify(r.msg,'err'); };
  return <div className="space-y-3"><Callout tone="info">Trạm đọc bình luận dưới bài seeding; câu hỏi mua / hỏi giá / xin liên hệ thành <b>lead</b> và giao việc cho MKT. Máy <b>không</b> tự trả lời lead — người trả lời bằng tài khoản phù hợp rồi đánh dấu.</Callout>
    <Tabs size="sm" active={loc} onChange={setLoc} tabs={[{key:'MOI',label:'Chưa trả lời'},{key:'ALL',label:'Tất cả'}]}/>
    {ds.length===0?<Empty>Chưa có lead.</Empty>:<Card pad="">{ds.map(l=>{ const v=viecCua(l.viec_id); const n=nhomCua(v.nhom_id); return <div key={l.id} className="px-3 py-2 border-b border-line/60 text-xs"><div className="flex items-center gap-2 flex-wrap"><Pill cls={l.trang_thai==='MOI'?'bg-amber-100 text-amber-800':l.trang_thai==='CHUYEN_SALE'?'bg-sky-100 text-sky-800':'bg-emerald-100 text-emerald-800'}>{l.trang_thai==='MOI'?'Mới':l.trang_thai==='CHUYEN_SALE'?'Chuyển Sales':'Đã trả lời'}</Pill><span className="font-semibold text-ink">{l.nguoi||'(ẩn danh)'}</span>{l.loai&&<Pill cls={l.loai==='TIEU_CUC'?'bg-rose-100 text-rose-700':l.loai==='HOI_MUA'?'bg-emerald-100 text-emerald-800':'bg-sky-100 text-sky-800'}>{({HOI_MUA:'hỏi mua',HOI_GIA:'hỏi giá',HOI_KY_THUAT:'hỏi kỹ thuật',TIEU_CUC:'tiêu cực'})[l.loai]||l.loai}{l.muc_do?(' · mức '+l.muc_do):''}</Pill>}<span className="text-ink-muted">· {n.ten||'—'} · {fmtDate(l.created_at)}</span>{l.link_bl&&<a className="text-brand-dark underline" href={l.link_bl} target="_blank" rel="noreferrer">mở bình luận</a>}{!chiXem&&l.trang_thai==='MOI'&&<div className="ml-auto flex gap-1"><Btn variant="ok" className="!py-1 !px-2 text-[11px]" onClick={()=>cap(l,'DA_TRA_LOI')} disabled={busy}>✓ Đã trả lời</Btn><Btn variant="ghost" className="!py-1 !px-2 text-[11px]" onClick={()=>cap(l,'CHUYEN_SALE')} disabled={busy}>→ Sales</Btn></div>}</div><div className="text-ink mt-0.5">“{l.noi_dung_hoi}”</div>{l.goi_y&&<div className="text-[11px] text-brand-dark mt-0.5">🤖 gợi ý trả lời: {l.goi_y}</div>}{l.ghi_chu&&<div className="text-[11px] text-ink-muted">{l.tra_loi_boi}: {l.ghi_chu}</div>}</div>; })}</Card>}</div>;
}
// ADR-007b — bình luận dẫn dắt (tài khoản khác) & nuôi tài khoản
const BL_TT={CHO:['Chờ giờ','bg-slate-100 text-ink'],DANG_GUI:['Đang gửi Trạm','bg-sky-100 text-sky-800'],DA_DANG:['Đã bình luận','bg-emerald-100 text-emerald-800'],LOI:['Lỗi','bg-rose-100 text-rose-700'],HUY:['Huỷ','bg-slate-100 text-ink-muted']};
function SeedingBinhLuan({S, chiXem}){
  const { db, goi, notify } = useApp(); const [busy,setBusy]=useState(false); const tk=id=>((S.tai_khoan||[]).find(t=>t.id===id)||{}); const nh=id=>((S.nhom||[]).find(n=>n.id===id)||{}); const vc=id=>((S.viec||[]).find(v=>v.id===id)||{}); const cfg=(db.module_config||{}).seeding||{};
  const hanh=async(b,hd)=>{ setBusy(true); const r=await goi('/seeding/binh-luan/'+b.id+'/'+hd,{method:'POST',body:{}}); setBusy(false); if(r.ok) notify('Đã cập nhật'); else notify(r.msg,'err'); };
  const huyNuoi=async(x)=>{ setBusy(true); const r=await goi('/seeding/nuoi/'+x.id+'/huy',{method:'POST',body:{}}); setBusy(false); if(r.ok) notify('Đã huỷ'); else notify(r.msg,'err'); };
  return <div className="space-y-3">
    <Callout tone="info">Sau khi bài lên, máy cho <b>{cfg.binh_luan_moi_bai}</b> tài khoản khác trong nhóm bình luận theo vai (hỏi kinh nghiệm · xác nhận · hỏi mua) sau {cfg.binh_luan_tre_min}–{cfg.binh_luan_tre_max} phút. Mỗi tài khoản mỗi ngày <b>{cfg.nuoi_moi_ngay}</b> lượt nuôi: vào nhóm xem {cfg.nuoi_phut} phút, thả {cfg.nuoi_tim} tim. Gặp checkpoint ≥ {cfg.checkpoint_ha_nhip} lần/30 ngày → máy tự hạ nhịp tài khoản; nhóm bị gỡ ≥ {cfg.go_bai_ha_nhip} bài/30 ngày → tự hạ nhịp nhóm (tăng nhịp phải qua G4).</Callout>
    <Card pad=""><div className="px-3 py-2 border-b border-line"><SectionTitle>Bình luận dẫn dắt ({(S.binh_luan||[]).length})</SectionTitle></div>
      {(S.binh_luan||[]).length===0?<Empty>Chưa có bình luận nào — sẽ tự lên lịch khi bài seeding đăng thành công.</Empty>:<div className="divide-y divide-line">{(S.binh_luan||[]).slice(0,80).map(b=>{ const v=vc(b.viec_id); return <div key={b.id} className="px-3 py-1.5 text-xs flex items-center gap-2 flex-wrap"><Pill cls={(BL_TT[b.trang_thai]||[])[1]}>{(BL_TT[b.trang_thai]||[])[0]}</Pill><span className="font-semibold text-ink">{tk(b.tai_khoan_id).nhan||'—'}</span><span className="text-ink-muted">{VAI_BL[b.vai]||b.vai} · {nh(v.nhom_id).ten||'—'} · {fmtDate(b.gio)}</span><span className="text-ink truncate max-w-[320px]">“{b.text}”</span>{v.link&&<a className="text-brand-dark underline" href={v.link} target="_blank" rel="noreferrer">bài</a>}{b.loi&&<span className="text-rose-600">· {b.loi}</span>}
        {!chiXem&&['CHO','DANG_GUI','LOI'].includes(b.trang_thai)&&<div className="ml-auto flex gap-1"><Btn variant="ghost" className="!py-0.5 !px-1.5 text-[11px]" onClick={()=>hanh(b,'da-dang')} disabled={busy}>✓ đã bình luận tay</Btn><Btn variant="ghost" className="!py-0.5 !px-1.5 text-[11px]" onClick={()=>hanh(b,'huy')} disabled={busy}>Huỷ</Btn></div>}</div>; })}</div>}</Card>
    <Card pad=""><div className="px-3 py-2 border-b border-line"><SectionTitle>Nuôi tài khoản (14 ngày)</SectionTitle></div>
      {(S.nuoi||[]).length===0?<Empty>Chưa có lượt nuôi — máy lên lịch mỗi sáng cho tài khoản đang bật có nhóm.</Empty>:<div className="divide-y divide-line">{(S.nuoi||[]).slice(0,60).map(x=><div key={x.id} className="px-3 py-1.5 text-xs flex items-center gap-2 flex-wrap"><Pill cls={x.trang_thai==='XONG'?'bg-emerald-100 text-emerald-800':x.trang_thai==='LOI'?'bg-rose-100 text-rose-700':x.trang_thai==='HUY'?'bg-slate-100 text-ink-muted':'bg-slate-100 text-ink'}>{x.trang_thai==='XONG'?'Xong':x.trang_thai==='DANG_GUI'?'Trạm đang làm':x.trang_thai}</Pill><span className="font-semibold text-ink">{tk(x.tai_khoan_id).nhan||'—'}</span><span className="text-ink-muted">{nh(x.nhom_id).ten||'—'} · {fmtDate(x.gio)} · {x.phut} phút · {x.tim} tim{x.ket_qua.tim!=null?(' → thả '+x.ket_qua.tim+' tim, xem '+x.ket_qua.xem_phut+' phút'):''}{x.ket_qua.loi?(' · '+x.ket_qua.loi):''}</span>{!chiXem&&['CHO','DANG_GUI'].includes(x.trang_thai)&&<LinkBtn className="ml-auto" onClick={()=>huyNuoi(x)}>Huỷ</LinkBtn>}</div>)}</div>}</Card>
  </div>;
}
function SeedingNghiNgo({S, chiXem}){
  const { goi, notify } = useApp(); const [ly,setLy]=useState({}); const [busy,setBusy]=useState(false);
  const ds=(S.viec||[]).filter(v=>v.trang_thai==='NGHI_NGO'); const nhomCua=id=>(S.nhom||[]).find(n=>n.id===id)||{}; const btCua=id=>(S.bien_the||[]).find(b=>b.id===id)||{};
  const quyet=async(v,q)=>{ setBusy(true); const r=await goi('/seeding/viec/'+v.id+'/quyet',{method:'POST',body:{quyet:q, ly_do:ly[v.id]||''}}); setBusy(false); if(r.ok) notify('Đã quyết — máy học (B16)'); else notify(r.msg,'err'); };
  return <div className="space-y-3"><Callout tone="warn">Máy đánh NGHI NGỜ khi: link trùng việc khác, react bất thường, hoặc không kiểm được bằng chứng sau 10 ngày. Người quyết Đạt / Không đạt — mỗi quyết định là mẫu học B16.</Callout>
    {ds.length===0?<Empty>Không có việc nghi ngờ.</Empty>:<Card pad="">{ds.map(v=>{ const n=nhomCua(v.nhom_id), b=btCua(v.bien_the_id); return <div key={v.id} className="px-3 py-2 border-b border-line/60 text-xs"><div className="font-semibold text-ink">{n.ten} · {fmtDate(v.dang_at)} {v.link&&<a className="text-brand-dark underline ml-1" href={v.link} target="_blank" rel="noreferrer">link</a>}</div><div className="text-amber-700">{v.ly_do}</div><div className="text-ink-muted line-clamp-2 mt-0.5">{b.noi_dung}</div>{!chiXem&&<div className="flex gap-1 mt-1 items-center"><Input className="!py-1 !px-2 text-[11px] !w-56" placeholder="lý do" value={ly[v.id]||''} onChange={e=>setLy({...ly,[v.id]:e.target.value})}/><Btn variant="ok" className="!py-1 !px-2 text-[11px]" onClick={()=>quyet(v,'DAT')} disabled={busy}>✓ Đạt</Btn><Btn variant="ghost" className="!py-1 !px-2 text-[11px]" onClick={()=>quyet(v,'KHONG_DAT')} disabled={busy}>✗ Không đạt</Btn></div>}</div>; })}</Card>}</div>;
}
function SeedingHieuQua({S}){
  const { db } = useApp(); const vs=(S.viec||[]); const da=vs.filter(v=>['DAT','KHONG_DAT','NGHI_NGO','DA_DANG'].includes(v.trang_thai)); const dat=vs.filter(v=>v.trang_thai==='DAT');
  const tong=(k)=>dat.reduce((s,v)=>s+Number((v.kiem||{})[k]||0),0); const btCua=id=>(S.bien_the||[]).find(b=>b.id===id)||{}; const tdCua=id=>(S.thong_diep||[]).find(t=>t.id===id)||{};
  const nhom=(arr,key)=>{ const m={}; arr.forEach(v=>{ const k=key(v)||'—'; m[k]=m[k]||{n:0,react:0,bl:0,lead:0}; m[k].n++; m[k].react+=Number((v.kiem||{}).react||0); m[k].bl+=Number((v.kiem||{}).binh_luan||0); m[k].lead+=Number((v.kiem||{}).lead||0); }); return Object.entries(m).sort((a,b)=>(b[1].react+2*b[1].bl+5*b[1].lead)/b[1].n-(a[1].react+2*a[1].bl+5*a[1].lead)/a[1].n); };
  const Bang=({tieu, rows})=><Card pad=""><div className="px-3 py-2 border-b border-line"><SectionTitle>{tieu}</SectionTitle></div>{rows.length===0?<Empty>Chưa có bài đạt.</Empty>:<table className="w-full text-xs"><thead><tr className="text-left text-ink-muted"><th className="px-3 py-1">—</th><th className="px-3 py-1">Bài</th><th className="px-3 py-1">React/bài</th><th className="px-3 py-1">BL/bài</th><th className="px-3 py-1">Lead</th></tr></thead><tbody>{rows.map(([k,r])=><tr key={k} className="border-t border-line/60"><td className="px-3 py-1 font-semibold text-ink">{k}</td><td className="px-3 py-1">{r.n}</td><td className="px-3 py-1">{Math.round(r.react/r.n)}</td><td className="px-3 py-1">{Math.round(r.bl/r.n)}</td><td className="px-3 py-1">{r.lead}</td></tr>)}</tbody></table>}</Card>;
  const dx=(db.de_xuat||[]).filter(d=>/^SEEDING_/.test(d.loai)&&d.trang_thai==='CHO');
  return <div className="space-y-3">
    <div className="grid grid-cols-2 md:grid-cols-5 gap-2">{[['Bài đã đăng (60 ngày)',da.length],['Đạt',dat.length],['React',tong('react')],['Bình luận',tong('binh_luan')],['Lead',(S.lead||[]).length]].map(([l,v])=><Card key={l} pad="p-3"><div className="text-[11px] text-ink-muted">{l}</div><div className="text-xl font-display font-extrabold text-ink">{v}</div></Card>)}</div>
    {dx.length>0&&<Callout tone="info">Máy có {dx.length} đề xuất seeding đang chờ duyệt ở Kết quả › Đề xuất (G4): {dx.map(d=>d.tieu_de).join(' · ')}</Callout>}
    <div className="grid md:grid-cols-3 gap-2"><Bang tieu="Theo thông điệp" rows={nhom(dat,v=>tdCua(btCua(v.bien_the_id).thong_diep_id).ten)}/><Bang tieu="Theo giọng" rows={nhom(dat,v=>GIONG_LABEL[btCua(v.bien_the_id).giong])}/><Bang tieu="Theo dạng bài" rows={nhom(dat,v=>DANG_LABEL[btCua(v.bien_the_id).dang_bai])}/></div>
    <Callout tone="note">Máy học (B17) mỗi tháng từ bảng này: nhóm bị gỡ bài ≥ 40% → đề xuất tắt; giọng / thông điệp kéo tương tác + lead gấp 1.5× → đề xuất ưu tiên. Người duyệt ở G4 mới áp dụng.</Callout>
  </div>;
}
