// ===== DÒNG SẢN PHẨM · TAB MÔ HÌNH (ADR-018: nhãn nằm ở bảng mau_doan; Kho mẫu / Bộ nhãn ở 86-nhanmau.jsx) =====
// Dòng sản phẩm: dòng đến từ 3 chỗ — Danh mục sản phẩm · luật tên thư mục/kênh khi học video · sửa tay từng video. Đổi tên / gộp một lần là đổi ở cả ba.
function DongSanPham() {
  const { me, goi, notify } = useApp(); const duoc = laGat(me); const [d, setD] = useState(null); const [ten, setTen] = useState({}); const [ax, setAx] = useState([]); const [busy, setBusy] = useState(false);
  const tai = async () => { const r = await goi('/dong-san-pham'); if (r.ok) { setD(r); setAx(r.anh_xa_dong || []); } else notify(r.msg, 'err'); };
  useEffect(() => { tai(); }, []);
  const doiTen = async (tu) => { const sang = (ten[tu] || '').trim(); if (!sang) return notify('Gõ tên mới', 'err'); setBusy(true); const r = await goi('/dong-san-pham/doi-ten', { method: 'POST', body: { tu, sang } }); setBusy(false); if (r.ok) { notify('Đã đổi "' + tu + '" → "' + sang + '"'); setTen({ ...ten, [tu]: '' }); setD(r); setAx(r.anh_xa_dong || []); } else notify(r.msg, 'err'); };
  const luuLuat = async () => { setBusy(true); const r = await goi('/cau-hinh/huan_luyen', { method: 'PUT', body: { cau_hinh: { anh_xa_dong: ax.filter(x => x.chua && x.dong).map(x => ({ chua: x.chua.trim(), dong: x.dong.trim() })) } } }); setBusy(false); if (r.ok) { notify('Đã lưu luật nhận dòng — máy học dùng từ lượt sau'); tai(); } else notify(r.msg, 'err'); };
  if (!d) return <Card pad="p-3"><Empty>Đang tải dòng sản phẩm…</Empty></Card>;
  const danhSach = d.dong.filter(x => x.dong !== '(chưa có)').map(x => x.dong);
  return <Card pad="p-3" className="space-y-3">
    <div><SectionTitle>Dòng sản phẩm</SectionTitle><div className="text-[11px] text-ink-muted">Dòng đến từ ba chỗ: <b>Danh mục sản phẩm</b> (Chiến lược › Danh mục › Sản phẩm, ô Dòng), <b>luật nhận dòng</b> khi máy học video (tên thư mục Drive / kênh chứa chữ gì), và <b>sửa tay từng video</b> ở danh sách video bên dưới. Dòng sai tên thì đổi tên ở bảng này, gõ tên dòng đã có để <b>gộp</b>: đổi một lần là đổi ở sản phẩm, video và kho mẫu.</div></div>
    <div className="overflow-x-auto"><table className="w-full text-xs min-w-[560px]"><thead><tr className="text-left text-ink-muted"><th className="px-2 py-1">Dòng</th><th className="px-2 py-1 text-right">Sản phẩm</th><th className="px-2 py-1 text-right">Video học</th><th className="px-2 py-1 text-right">Footage</th><th className="px-2 py-1 text-right">Mẫu</th><th className="px-2 py-1">Đổi tên / gộp vào</th></tr></thead>
      <tbody>{d.dong.map(x => <tr key={x.dong} className="border-t border-line/60"><td className="px-2 py-1 font-semibold text-ink">{x.dong}</td><td className="px-2 py-1 text-right tabular-nums">{x.san_pham}</td><td className="px-2 py-1 text-right tabular-nums">{x.video}</td><td className="px-2 py-1 text-right tabular-nums">{x.footage}</td><td className="px-2 py-1 text-right tabular-nums">{x.mau}</td>
        <td className="px-2 py-1">{duoc && x.dong !== '(chưa có)' ? <div className="flex gap-1"><Input className="!py-0.5 !px-1.5 text-[11px] !w-36" list="ds-dong-doi" placeholder="tên đúng" value={ten[x.dong] || ''} onChange={e => setTen({ ...ten, [x.dong]: e.target.value })} /><Btn variant="ghost" className="!py-0.5 !px-2 text-[11px]" disabled={busy} onClick={() => doiTen(x.dong)}>Đổi</Btn></div> : x.dong === '(chưa có)' ? <span className="text-[10px] text-ink-muted">gán dòng cho từng video ở danh sách bên dưới</span> : null}</td></tr>)}</tbody></table>
      <datalist id="ds-dong-doi">{danhSach.map(x => <option key={x} value={x} />)}</datalist></div>
    <div><div className="font-semibold text-ink text-xs mb-1">Luật nhận dòng khi học video</div><div className="text-[11px] text-ink-muted mb-1">Tên thư mục hoặc kênh <b>chứa</b> chữ ở cột trái (không phân biệt hoa thường, có dấu hay không) thì video thuộc dòng ở cột phải. Luật trên cùng khớp trước. Không khớp luật nào thì để trống dòng, không đoán.</div>
      <div className="space-y-1">{ax.map((x, i) => <div key={i} className="flex gap-1 items-center max-w-md"><Input className="!py-0.5 !px-1.5 text-[11px] flex-1 min-w-0" value={x.chua} disabled={!duoc} placeholder="chữ trong tên thư mục, vd FINEX" onChange={e => setAx(ax.map((y, j) => j === i ? { ...y, chua: e.target.value } : y))} /><span className="text-ink-muted">→</span><Input className="!py-0.5 !px-1.5 text-[11px] flex-1 min-w-0" list="ds-dong-doi" value={x.dong} disabled={!duoc} placeholder="dòng" onChange={e => setAx(ax.map((y, j) => j === i ? { ...y, dong: e.target.value } : y))} />{duoc && <Btn variant="ghost" className="!py-0.5 !px-1.5 text-[11px]" onClick={() => setAx(ax.filter((_, j) => j !== i))}>✕</Btn>}</div>)}</div>
      {duoc && <div className="flex gap-1 mt-1"><Btn variant="ghost" className="!py-1 !px-2 text-[11px]" onClick={() => setAx([...ax, { chua: '', dong: '' }])}>＋ Thêm luật</Btn><Btn variant="brand" className="!py-1 !px-3 text-[11px]" disabled={busy} onClick={luuLuat}>Lưu luật</Btn></div>}</div>
  </Card>;
}

// ===== các tab con đã gom (25/09, chủ: "hệ thống lại ui của tất cả sub tab bộ não AI có bị chồng chéo thì gom gọn lại") =====
function PhienBanDs({ a }) {
  const pbs = a.phien_ban || [];
  return <Card pad=""><div className="px-3 py-2 border-b border-line flex items-center gap-2"><SectionTitle>Phiên bản mô hình</SectionTitle><span className="text-[11px] text-ink-muted">lịch sử; bản chờ duyệt bật / từ chối ở tab Dạy máy</span></div>
    {!pbs.length ? <Empty>Chưa có phiên bản nào.</Empty> : <div className="divide-y divide-line">{pbs.map(p => <div key={p.id} className="px-3 py-1.5 text-xs flex items-center gap-2 flex-wrap"><Pill cls={p.trang_thai === 'DUYET' ? 'bg-emerald-100 text-emerald-800' : p.trang_thai === 'TU_CHOI' ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-800'}>{p.trang_thai === 'CHO_DUYET' ? 'chờ duyệt' : p.trang_thai === 'DUYET' ? 'đang dùng' : 'từ chối'}</Pill><b className="text-ink">{p.tinh_nang} · {p.phien_ban}</b>{p.pham_vi && p.pham_vi !== 'chung' && <Pill cls="bg-sky-100 text-sky-800">{TEN_PV(p.pham_vi)}</Pill>}<span className="text-ink-muted">khớp người {p.danh_gia.diem}/100 trên {p.danh_gia.n_kiem} mẫu kiểm (cách cũ {p.danh_gia.diem_truoc}) · {p.may} · {fmtDate(p.created_at)}{p.duyet_boi ? ' · ' + p.duyet_boi + (p.ly_do ? ': ' + p.ly_do : '') : ''}</span></div>)}</div>}
  </Card>;
}
// ADR-018: tab Mô hình gom phần vận hành (bàn huấn luyện, tiến trình, nạp dữ liệu, video đã học) + danh mục mô hình / định tuyến
function MoHinhNao({ a, setTab }) {
  const { db, me } = useApp(); const duoc = laGat(me); const dongs = a.dong_san_pham || [];
  return <div className="space-y-3"><BanHuanLuyen a={a} setTab={setTab} /><KyNang a={a} duoc={duoc} db={db} /><PhienBanDs a={a} /><TienTrinh a={a} db={db} /><KhoMau a={a} duoc={duoc} dongs={dongs} /><NhatKyHoc a={a} /><HuanLuyenAI a={a} phan="mo_hinh" /><MoHinhAI a={a} /><DinhTuyenAI a={a} /></div>;
}
function ChiPhiNao({ a }) { return <div className="space-y-3"><ChiPhiMoHinh a={a} /><KhoaAPI /></div>; }
